/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-30 05:23:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction loginPopup() {\r\n");
      out.write("\t\twindow.open(\"./MemberLogin.me\", \"a\",\"width=483, height=422, left=900, right=0, top=500 resizable = no, scrollbars = no\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction SendMailPopup(){\r\n");
      out.write("\t\twindow.open(\"./SendMail.me\",\"b\",\"width=450, height=500, left=900, right=0, top=500 resizable = no, scrollbars = no\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction BasketListPopup(){\r\n");
      out.write("\t\twindow.open(\"./BasketList.ba\",\"c\",\"width=700, height=450, left=900, right=0, top=500 resizable = no, scrollbars = no\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction MapPopup(){\r\n");
      out.write("\t\twindow.open(\"./map.jsp\",\"d\",\"width=500, height=400, left=900, right=0, top=300 resizable = no, scrollbars = no\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
	
	String id = (String) session.getAttribute("f_mem_id");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"head\">\r\n");
      out.write("\t<div class=\"gnb_wrap\">\r\n");
      out.write("\t\t<div class=\"gnb_util\">\r\n");
      out.write("\t\t\t<div class=\"util_wrap\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t");

					if(id == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='./MemberJoin.me'\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t<li onclick=\"loginPopup();\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">로그인</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><label><b style=\"color:#ccff66;\">");
      out.print(id );
      out.write("님</b></label></li>\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='./MemberLogout.me'\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">로그아웃</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t<li onclick=\"location.href='./MemberMyPageAction.me'\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\">마이페이지</a></li> -->\t\t\t\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li onclick=\"location.href='./QNABoard.me'\"><a>고객행복센터</a></li>\r\n");
      out.write("\t\t\t\t\t <!-- <li onclick=\"MapPopup();\"><a>실시간 교통정보</a></li> -->\r\n");
      out.write("\t\t\t\t");

					if(id == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a\r\n");
      out.write("\t\t\t\t\t\thref=\"#\"\r\n");
      out.write("\t\t\t\t\t\ttarget=\"_blank\">카카오톡가입</a></li> -->\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"gnb_menu\">\r\n");
      out.write("\t\t\t<!-- <h1 class=\"logo\"> </h1> --><a href=\"./Main.me\">\r\n");
      out.write("\t\t\t<img src=\"./cjkit/web/images/cook_img/logoC.png\" class=\"logo\">\r\n");
      out.write("\t\t\t\t<span class=\"hide\">라따뚜이</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"list_gmenu\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"./MemberIntroduce.me\" target=\"_self\">소개</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"./RecipeList.re\" target=\"_self\">레시피</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li><a href=\"./GoodResMainAction.gr\" target=\"_self\">맛집</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"./GoodsList.go\">쇼핑</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if(id != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"./MemberMyPageAction.me\">MY PAGE</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"my_gmenu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<!--                        <li class=\"g_my\"><a href=\"/pc/my/myMain\"><span class=\"hide\">마이 쿡킷 페이지로 이동</span></a></li> 0701 숨김처리 -->\r\n");
      out.write("\t\t\t\t\t<li class=\"g_od\"><a\r\n");
      out.write("\t\t\t\t\t\tonclick=\"BasketListPopup();\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"txt\">장바구니</span> <span class=\"hide\">장바구니 페이지로\r\n");
      out.write("\t\t\t\t\t\t\t\t이동</span> <!--   <span class=\"num\" id=\"headerCartCount\">\r\n");
      out.write("                                   <span class=\"hide\">장바구니에 담기 상품 갯수</span>\r\n");
      out.write("                                   0\r\n");
      out.write("                               </span> --> <!-- 장바구니 담는 갯수는 구현이 안되어서 주석처리함. -->\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"g_mu\"><a\r\n");
      out.write("\t\t\t\t\t\tonclick=\"SendMailPopup();\"><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"txt\">관리자에게..</span><span class=\"hide\">관리자에게 메일보내기</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
