/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-31 14:26:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.member.db.MemberBean;

public final class MemberUpdateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.member.db.MemberBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>라따뚜이</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function btn_click(str) {\r\n");
      out.write("\tif(str == \"modify\") {\r\n");
      out.write("\t\tuserInfo.action = \"./MemberUpdateAction.me\"\r\n");
      out.write("\t} else if(str == \"delete\") {\r\n");
      out.write("\t\tuserInfo.action = \"./MemberDeleteAction.me\"\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"./cjkit/web/css/memberCSS/memberUpdateForm.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/common.css?20200924090025\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/main.css?20200924090025\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../cjkit/mobile/css/swiper.css\">\r\n");
      out.write("<script src=\"./js/memberJS/insertScript.js\" ></script>\r\n");
      out.write("<script src=\"./js/memberJS/idCheckScript.js\" ></script>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String f_mem_id = (String)session.getAttribute("f_mem_id");
		
		if(f_mem_id == null) {
			response.sendRedirect("./Main.me");
		}	
		MemberBean mb = (MemberBean) request.getAttribute("mb");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"div_backImg\">\r\n");
      out.write("\t\t<!-- <img class=\"imgBack\" src=\"./cjkit/web/images/cook_img/memberJoin.jpg\"> -->\r\n");
      out.write("\t\t<div class=\"insertTitle\"><label>회원 정보</label></div>\t\r\n");
      out.write("\t\t<div class=\"div01\">\t\t\t\r\n");
      out.write("\t\t\t<form name=\"userInfo\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table class=\"tab01\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>아아디</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_id\" value=\"");
      out.print(mb.getF_mem_id() );
      out.write("\" readonly=\"readonly\"></td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"idDup\" value=\"idUncheck\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>비밀번호</td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"f_mem_pw\" maxlength=\"10\" placeholder=\"최소 4자 최대 10자 가능.\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>비밀번호확인</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"f_mem_pw_chk\" maxlength=\"10\" onkeyup=\"pwCheck()\"></td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"div01_inp_pwChkRes\" type=\"text\" name=\"f_mem_pw_result\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>이름</td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_name\" value=\"");
      out.print(mb.getF_mem_name() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>휴대폰</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_phone\" value=\"");
      out.print(mb.getF_mem_phone() );
      out.write("\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>우편번호</td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_postcode\" id=\"postcode\" value=\"");
      out.print(mb.getF_mem_postcode() );
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"div01_inp_postcode\" type=\"button\" value=\"주소검색\" onclick=\"daumPostcode()\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>주소</td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_address\" id=\"address\" value=\"");
      out.print(mb.getF_mem_address() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>상세주소</td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_detailAddress\" id=\"detailAddress\" value=\"");
      out.print(mb.getF_mem_detailAddress() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_extraAddress\" id=\"extraAddress\" value=\"");
      out.print(mb.getF_mem_extraAddress() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>이메일</td>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_email\" placeholder=\"이메일\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>닉네임</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"f_mem_nick\" placeholder=\"중복확인을 눌러주세요\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"div01_inp_idChk\" type=\"button\" value=\"중복확인\" onclick=\"openNickNameChk()\"></td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"nickNameDup\" value=\"nickNameUncheck\">\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"inp01\" type=\"submit\" value=\"수정\" onclick=\"btn_click('modify')\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"inp03\" type=\"submit\" value=\"회원탈퇴\" onclick=\"btn_click('delete')\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"inp02\" type=\"button\" value=\"취소\" onclick=\"location.href='./MemberMyPageAction.me'\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
