/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-30 06:25:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class popupLoginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1622352018889L));
    _jspx_dependants.put("jar:file:/C:/Users/isys1/OneDrive/바탕%20화면/아이티윌/workspace_food/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/food/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>라따뚜이</title>\r\n");
      out.write("<link href=\"./cjkit/web/css/memberCSS/popupLoginForm.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"div_image\">\r\n");
      out.write("    <img src=\"./cjkit/web/images/cook_img/pop.png\">\r\n");
      out.write("      <div class=\"div01\">\r\n");
      out.write("         <div class=\"div02\" style=\"text-align: center;\">\r\n");
      out.write("         <label><b>회원로그인</b></label></div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"div03\">\t\r\n");
      out.write("\t\t\t\t<form action=\"./MemberLoginAction.me\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<label class=\"lab01\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"tab01\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"tab01_input01\" type=\"text\" name=\"f_mem_id\" placeholder=\"아이디\"></td>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"tab01_input01\" type=\"password\" name=\"f_mem_pw\" placeholder=\"비밀번호\"></td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"tab01_input02\" type=\"submit\" value=\"로그인\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</table>\t\t\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <div class=\"div02\"><label>간편로그인</label></div>\r\n");
      out.write("\t\t\t <div class=\"div04\">\r\n");
      out.write("\t\t\t\t<table class=\"tab02\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tab02_td01\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>소셜계정으로 간편하게 로그인하세요.<br>더 나은 서비스로 나아갑니다 !!</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"tab02_td02\" type=\"button\" value=\"카카오 로그인 >\">\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\t\t\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t\t<div class=\"div05\">\r\n");
      out.write("\t\t\t\t<table class=\"tab03\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tab03_td01\"><a class=\"tab03_a01\" onclick=\"memberJoin()\"><label>회원가입</label></a></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tab03_td04\">|</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tab03_td02\"><a class=\"tab03_a01\" onclick=\"location.href='./MemberIdSearch.me'\"><label>아이디 찾기</label></a></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tab03_td04\">|</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"tab03_td03\"><a class=\"tab03_a01\" onclick=\"location.href='./MemberPwSearch.me'\"><label>비밀번호 찾기</label></a></td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\t\r\n");
      out.write("\t\tfunction memberJoin() {\r\n");
      out.write("\t\t\tself.close();\r\n");
      out.write("\t\t\topener.location.href=\"./MemberJoin.me\";\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction memberIdSearch() {\r\n");
      out.write("\t\t\tself.close();\r\n");
      out.write("\t\t\twinodw.opne(\"./MemberIdSearch.me\", \"memberIdSearch\",\"width=300, height=300, left=900, right=0, top=500 resizable = no, scrollbars = no\");\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction memberPwSearch() {\r\n");
      out.write("\t\t\tself.close();\r\n");
      out.write("\t\t\twinodw.opne(\"./MemberPwSearch.me\", \"memberIdSearch\",\"width=300, height=300, left=900, right=0, top=500 resizable = no, scrollbars = no\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
