/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-31 12:37:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.recipe.board.db.RecipeBean;
import java.util.ArrayList;
import java.util.List;
import com.goodres.db.GoodResBoardBean;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.goodres.db.GoodResBoardBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.recipe.board.db.RecipeBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.cjcookit.com/pc/main by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Mar 2021 09:53:44 GMT -->\r\n");
      out.write("<!-- Added by HTTrack --><meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" /><!-- /Added by HTTrack -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"셰프의 레시피와 신선 재료가 새벽배송으로 문 앞까지! 오늘부터 나도 셰프! CJ쿡킷\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<title>라따뚜이</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"https://www.cjcookit.com/cjkit/web/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/common.css?20200924090025\">\r\n");
      out.write("<!--     <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/chatbot.css?20200924090025\">\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write(" <!-- !!!!!!!!!!!!!!!!!!!!! 메인 슬라이더 태그 !!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("    $('.bxslider').bxSlider({\r\n");
      out.write("    \tauto: true,\r\n");
      out.write("    \tspeed: 500,\r\n");
      out.write("    \tpause: 5000,\r\n");
      out.write("    \tmode: 'horizontal',\r\n");
      out.write("    \tpager: false,\r\n");
      out.write("    \tcaptions: true\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- uri array -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- 업무 단위로 c:when 문 추가하여 사용하세요. -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/main.css?20200924090025\">\r\n");
      out.write("   \r\n");
      out.write("   \t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/goodResCSS/goodress_main.css\">\r\n");
      out.write("   \t\t\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"../cjkit/mobile/css/swiper.css\">\r\n");
      out.write("    \t<!-- <script type=\"text/javascript\" src=\"https://www.cjcookit.com/cjkit/mobile/js/library/swiper.min.js\"></script> -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../cjkit/web/js/libs/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar cjConf = {\r\n");
      out.write("\t\t\tserverImg : \"//www.cjcookit.com/cjkit/web/images\",\r\n");
      out.write("\t\t\tloginYn : \"N\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery/jquery.form.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/crew/crew17e0.js?20200924090026\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/crew/form/form17e0.js?20200924090026\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/cj17e0.js?20200924090026\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/oauth/kakao.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/oauth/naveridlogin_js_sdk_2.0.0.js\"></script>\r\n");
      out.write("<!-- \t<script type=\"text/javascript\" src=\"https://www.cjcookit.com/pc/js/netfunnel.js?20200924090026\" charset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.cjcookit.com/pc/js/om_pc_skin.js?20200924090026\" charset=\"utf-8\"></script> -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/webtoolkit.base64.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://nsso.cjone.com/findCookieSecured.jsp?cjssoq=sxFMCkAClfsIXKzOW%2BD6P812UfEpwkjmL7CLmvdfoq%2BkmPDF6xf2tiFnEQ3fwVv66X5vme2b7DBHIQtpiE3bj2o2MHp5bDRKRnk5RWRJN0txRlFVYjVqSEVLQVl1UWMzRzdkNFBkTm1pR3B4Rm5VdlhSQlhLc1JkdnZ1Z1hsQWdqcHZOdW1iazhzMD0%3D\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t//$(document).ready(function(evt){\r\n");
      out.write("\t\t\tif((typeof _cjssoEncData) != \"undefined\" && _cjssoEncData !=\"\"){\r\n");
      out.write("\t\t\t\tvar redirectUrl = location.pathname + location.search;\r\n");
      out.write("\t\t\t\tvar data = {};\r\n");
      out.write("\t\t\t\tdata.redirectUrl\t\t= redirectUrl;\r\n");
      out.write("\t\t\t\tdata.mode\t\t\t= \"SSO_AUTH\";\r\n");
      out.write("\t\t\t\tdata.cjssoq\t\t\t= _cjssoEncData;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 전송\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\tasync\t\t: true,\r\n");
      out.write("\t\t\t\t\turl\t\t\t: '/pc/auth/login.json',\r\n");
      out.write("\t\t\t\t\tdataType\t: 'json',\r\n");
      out.write("\t\t\t\t\ttype\t\t: 'POST',\r\n");
      out.write("\t\t\t\t\tdata\t\t: data,\r\n");
      out.write("\t\t\t\t\tsuccess\t\t: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\t\t\t// 로그인 처리 결과 체크\r\n");
      out.write("\t\t\t\t\t\tcj.loginResultCheck(data);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror\t   : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t  //console.log(jqXHR.status);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<meta name=\"google-site-verification\" content=\"0GuzYD2oaBVARveIoOEQEEx10478h5Vnn5i5YNAS6zI\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"ma_body\" >\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"skipnavi\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#container_title\">본문바로가기</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<div class=\"preloader\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<div class=\"loader\">\r\n");
      out.write("\t\t\t\t<span class=\"loading\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   <!-- header -->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("   <!-- header 끝-->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"container\" >\r\n");
      out.write("\t\t\t<div id=\"container_title\" class=\"hide\" tabindex=\"-1\">본문 시작</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- content -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- HTML_GEN_APPLY_PAGE -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- content -->\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("            <div class=\"main_wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- mainBillboard Start -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("               <!-- billboard -->\r\n");
      out.write("                <div class=\"ma_billboard\">\r\n");
      out.write("                    <div class=\"list_slide ui_carousel\">\r\n");
      out.write("                        <!-- indigator -->\r\n");
      out.write("                        <div class=\"indigator_pos\" style=\"display:none;\">\r\n");
      out.write("                            <div class=\"indigator silde_arrow_wrap\"> <!-- 스크립트요청사항 : 검정색 버전 .black 클래스 추가, 하얀색 버젼 .white 클래스 추가 -->\r\n");
      out.write("                                <button class=\"prev ui_carousel_prev ui_carousel_arrow\" style=\"display: inline-block;\"><span class=\"hide\">상품 이전보기</span></button>\r\n");
      out.write("                                <span class=\"count_wrap\">\r\n");
      out.write("                                    <span class=\"num\" ><em>1</em>/5</span>\r\n");
      out.write("                                    <span class=\"hide\">총 페이지 3 페이지 중 현재 1번째 페이지</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <button class=\"next ui_carousel_next ui_carousel_arrow\" style=\"display: inline-block;\"><span class=\"hide\">상품 다음보기</span></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t\t<!-- list -->\r\n");
      out.write("                        <div class=\"prod_list ui_carousel_list\">\r\n");
      out.write("                            <ul class=\"ui_carousel_track\">\r\n");
      out.write("                            \t\r\n");
      out.write(" \t\t\t\t\t\t\r\n");
      out.write("\t\t                                <li class=\"slide_conts white\"> <!-- 개발요청사항 : 검정색 버전 .black 클래스 추가, 하얀색 버젼 .white 클래스 추가 -->\r\n");
      out.write("\t\t                           \t\t\t<!-- content -->\r\n");
      out.write("\t\t\t<div id=\"content\" class=\"intro_content\">\r\n");
      out.write("                <h1 class=\"hide\">COOKIT 소개</h1>\r\n");
      out.write("                <!-- top -->\r\n");
      out.write("                <div class=\"top\">\r\n");
      out.write("                    <div class=\"intro_img_wrap\"> <!-- style=\"width:2560px; height:640px;\" -->\r\n");
      out.write("                       <ul class=\"bxslider\">\r\n");
      out.write("                        <li><img src=\"./cjkit/web/images/cook_img/main2.png\"> </li>                      \r\n");
      out.write("                        <li><img src=\"./cjkit/web/images/cook_img/main1.png\"> </li>                      \r\n");
      out.write("                        <li><img src=\"./cjkit/web/images/cook_img/main3.png\"> </li>                      \r\n");
      out.write("                        <li><img src=\"./cjkit/web/images/cook_img/main4.png\"> </li>                      \r\n");
      out.write("                        <li><img src=\"./cjkit/web/images/cook_img/main5.png\"> </li>                      \r\n");
      out.write("                       </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- 기획전 케이스 -->\r\n");
      out.write("  <div class=\"pro_module\">\r\n");
      out.write("  \t<!-- <a nohref target=\"_self\" class=\"vr_link\"> -->\r\n");
      out.write("  \t<a href=\"https://www.cjcookit.com/pc/event/planView?plnId=101743&amp;wid1=bnr_bn1\" class=\"vr_link\">\r\n");
      out.write(" \t        <span class=\"hide\">WEEKDAY SALE | 03. 22 ~ 03. 25COOKIT <br> 푸릇푸릇한 테이블</span>\r\n");
      out.write("   </a>\r\n");
      out.write("      <div class=\"img_wrap\">\r\n");
      out.write("          <!-- <a nohref target=\"_self\" class=\"conts\"> -->\r\n");
      out.write("          <a href=\"https://www.cjcookit.com/pc/event/planView?plnId=101743&amp;wid1=bnr_bn1\" class=\"conts\">\r\n");
      out.write("              <img src=\"../../img.cjcookit.com/images/file/display/903/2021032209162639668b0.jpg?RS=1920x640\" alt=\".\" onerror=\"cj.com.noImg(this)\">\r\n");
      out.write("          </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"txt_position\">\r\n");
      out.write("          <div class=\"txt_wrap\">\t\t                                                \r\n");
      out.write("              <a href=\"https://www.cjcookit.com/pc/event/planView?plnId=101743&amp;wid1=bnr_bn1\" class=\"conts\">\r\n");
      out.write("                  \r\n");
      out.write("                   \t<div class=\"prd_flag_wrap\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<span class=\"flag\">주중 이벤트</span>\r\n");
      out.write("\t\r\n");
      out.write("</div>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tit_info\">\r\n");
      out.write("                    <span class=\"sub_tit st_elps\">COOKIT <br> 푸릇푸릇한 테이블</span>\r\n");
      out.write("                    <span class=\"sub_discription_evt st_elps\">WEEKDAY SALE | 03. 22 ~ 03. 25</span>\t\t                                                        \r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //기획전 케이스 -->\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("  <li class=\"slide_conts white\"> <!-- 개발요청사항 : 검정색 버전 .black 클래스 추가, 하얀색 버젼 .white 클래스 추가 -->\r\n");
      out.write("      <!-- 기획전 케이스 -->\r\n");
      out.write("      <div class=\"pro_module\">\r\n");
      out.write("      \t<!-- <a nohref target=\"_self\" class=\"vr_link\"> -->\r\n");
      out.write("\t\t   <a href=\"https://www.cjcookit.com/pc/event/planView?plnId=101722&amp;wid1=bnr_bn3\" class=\"vr_link\">\r\n");
      out.write("\t        <span class=\"hide\">3월 한 달간(3/2~3/31)<br>\r\n");
      out.write("\t\t\t\t무료배송 혜택!3만원 이상 구매하면<br>\r\n");
      out.write("\t\t\t\t무료배송</span>\r\n");
      out.write("          </a>\r\n");
      out.write("             <div class=\"img_wrap\">\r\n");
      out.write("     <!-- <a nohref target=\"_self\" class=\"conts\"> -->\r\n");
      out.write("    <a href=\"https://www.cjcookit.com/pc/event/planView?plnId=101722&amp;wid1=bnr_bn3\" class=\"conts\">\r\n");
      out.write("        <img src=\"../../img.cjcookit.com/images/file/display/563/2021022615410231468b0.jpg?RS=1920x640\" alt=\".\" onerror=\"cj.com.noImg(this)\">\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"txt_position\">\r\n");
      out.write("    <div class=\"txt_wrap\">\t\t                                                \r\n");
      out.write("        <a href=\"https://www.cjcookit.com/pc/event/planView?plnId=101722&amp;wid1=bnr_bn3\" class=\"conts\">\r\n");
      out.write("                                      \r\n");
      out.write("                                       \t<div class=\"prd_flag_wrap\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<span class=\"flag\">무료배송</span>\r\n");
      out.write("\t\r\n");
      out.write("</div>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("     <div class=\"tit_info\">\r\n");
      out.write("      <span class=\"sub_tit st_elps\">3만원 이상 구매하면<br> 무료배송</span>\r\n");
      out.write("       <span class=\"sub_discription_evt st_elps\">3월 한 달간(3/2~3/31)<br>\r\n");
      out.write("\t\t\t\t무료배송 혜택!</span>\t\t                                                        \r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\t\t                                    <!-- //기획전 케이스 -->\r\n");
      out.write("                  </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\t\t\t                        \r\n");
      out.write(" <!-- mainBillboard End -->               \r\n");
      out.write("\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("<!--  <h1>내용 시작</h1> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// http://localhost:8080/cook_design/Main.me
	GoodResBoardBean grbb = new GoodResBoardBean();
	List<GoodResBoardBean> starAvgList = new ArrayList<GoodResBoardBean>();
	starAvgList = (List) request.getAttribute("starAvgList");
	
	RecipeBean rcpb = new RecipeBean();
	List<RecipeBean> rcpViewList = new ArrayList<RecipeBean>();
	rcpViewList = (List) request.getAttribute("rcpViewList");


      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t  \t\t<div style=\"margin: 100px; background-color: white;\">\r\n");
      out.write(" \t\t<div class=\"mainListImage\">\r\n");
      out.write("\t\t\t<span class=\"main_list_span2\"><h3><b>실시간 인기 레시피</b></h3><hr></span>\r\n");
      out.write("\t\t\t<table class=\"div_gr_list_table2\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");

					if(rcpViewList.size() > 2){
	 					for(int i=0;i<3;i++) {
								rcpb = rcpViewList.get(i);								
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<!-- 이미지 출력 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"./RecipeDetail.re?f_rcp_num=");
      out.print(rcpb.getF_rcp_num() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./recipe_upload/");
      out.print(rcpb.getF_rcp_th_img() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 10%;\" width=\"290\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</th>\t\t\t\t\r\n");
      out.write(" \t\t\t\t");

	 				}
				
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");

					for(int i=0; i<3; i++) {
						rcpb = rcpViewList.get(i);
						
				     
      out.write("\r\n");
      out.write("               <th class=\"gr_gu_name\">");
      out.print(rcpb.getF_rcp_title() );
      out.write("</th>\r\n");
      out.write("            ");

                  }
            
                  
      out.write("\r\n");
      out.write("                  ");

               } else {
            
      out.write("\r\n");
      out.write("                     <th>현재 인기 게시글이 없습니다</th>\r\n");
      out.write("            \r\n");
      out.write("            ");

               }
            
      out.write("\r\n");
      out.write("            </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>  \r\n");
      out.write("\r\n");
      out.write("  \t<div style=\"margin: 100px; background-color: white;\">\r\n");
      out.write(" \t\t<div class=\"mainListImage\">\r\n");
      out.write("\t\t\t<span class=\"main_list_span2\"><h3><b>평점이 높은 인기 식당</b></h3><hr></span>\r\n");
      out.write("\t\t\t<table class=\"div_gr_list_table2\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");

 					for(int i=0;i<4;i++) {
							grbb = starAvgList.get(i);						
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<!-- 이미지 출력 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"./GoodResContentAction.gr?num=");
      out.print(grbb.getF_gr_num() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(grbb.getF_gr_img() );
      out.write("\" style=\"border-radius: 10%;\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</th>\t\t\t\t\r\n");
      out.write(" \t\t\t\t");

 					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t");

					for(int i=0; i<4; i++) {
						grbb = starAvgList.get(i);
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<th class=\"gr_gu_name\">");
      out.print(grbb.getF_gr_name() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>  \r\n");
      out.write(" \r\n");
      out.write(" <div class=\"main_img\">\r\n");
      out.write("  \t<img src=\"intro_cookit_4.jpg\"> \r\n");
      out.write(" \t<p>\r\n");
      out.write(" \t\t혼자 알기 아까운 나만의 요리비법, <br>\r\n");
      out.write(" \t\t라따뚜이에서 공유해보세요! <br><br>\r\n");
      out.write(" \t\t<a href=\"./GoodsList.go\"> &gt &gt 쇼핑몰 바로가기 </a>  \r\n");
      out.write(" \t</p>\r\n");
      out.write(" \t\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(evt){\r\n");
      out.write("\t\t// 개인화 영역 구성\r\n");
      out.write("\t\tcreatePersonOrder();\r\n");
      out.write("\t\tcreatePersonCpn();\r\n");
      out.write("\r\n");
      out.write("\t\t// 쿠키 저장된 배너 노출여부가 close이면 배너 노출 안하도록 설정\r\n");
      out.write("\t\tif (getCookie('mainTopBrn') != \"close\") {\r\n");
      out.write("\t\t\tcreateMainTopBrn();\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\t// 이벤트 팝업\r\n");
      out.write("\t\t\tif (getCookie('mainEventPop') != \"close\") {\r\n");
      out.write("\t\t\t\tshowEventPop();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$.each($(\"img[name^=imgResizingCookitReview]\"), function(index, item){\r\n");
      out.write("\t\t\tvar imgObject = {};\r\n");
      out.write("\t\t\timgObject.url = $(this).attr(\"url\");\r\n");
      out.write("\t\t\timgObject.w = 0;\r\n");
      out.write("\t\t\timgObject.h = 0;\r\n");
      out.write("\t\t\timgObject.obj = this;\r\n");
      out.write("\t\t\timage.init(imgObject);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcj.com.lazyLoad();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 빌보드영역 동영상 재생 시 텍스트 컬러 변경\r\n");
      out.write("\t\t$('.ma_billboard .slide_conts video').on('playing',function(e){\t\t\t\r\n");
      out.write("            var $slideConts = $(this).closest('.slide_conts');\r\n");
      out.write("            var color = $slideConts.attr('video_color');\r\n");
      out.write("            if(cj.isEmpty(color)) color = $slideConts.attr('image_color');\r\n");
      out.write("            $slideConts.removeClass('black').removeClass('white').addClass(color);\r\n");
      out.write("            \r\n");
      out.write("            var currentColor = $('.ma_billboard .ui_carousel_current').hasClass('black')?'black':'white';\r\n");
      out.write("           \t$('.ma_billboard .indigator').removeClass('black').removeClass('white').addClass(currentColor);\r\n");
      out.write("     \t}).on('ended',function(e){\r\n");
      out.write("\t\t\tvar $slideConts = $(this).closest('.slide_conts');\r\n");
      out.write("            var color = $slideConts.attr('image_color');\r\n");
      out.write("            $slideConts.removeClass('black').removeClass('white').addClass(color);\r\n");
      out.write("            \r\n");
      out.write("            var currentColor = $('.ma_billboard .ui_carousel_current').hasClass('black')?'black':'white';\r\n");
      out.write("           \t$('.ma_billboard .indigator').removeClass('black').removeClass('white').addClass(currentColor);\r\n");
      out.write("     \t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t// $('#wrap').vcMain(); 실행 후 처리되어야 할 작업\r\n");
      out.write("\tfunction initMain(){\r\n");
      out.write("\t\t// 맛취향 개인화 설정\r\n");
      out.write("\t\tsetFlvrTst();\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".main_wrap\").off('click', 'button.btn_resel');\t//재판매알림 토글 수동처리\r\n");
      out.write("        $(\".main_wrap\").off('click', 'button.btn_ar_new');\t//신메뉴알림 토글 수동처리\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//쿠키에 저장된 값 가져오기\r\n");
      out.write("\tfunction getCookie(name) {\r\n");
      out.write("\t\tvar value = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');\r\n");
      out.write("\t\treturn value? value[2] : null;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction createMainTopBrn(){\r\n");
      out.write("\t\t// 요청처리\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl\t\t\t: \"/pc/main/getMainTopBrnList.json\",\r\n");
      out.write("\t\t\tdataType\t: \"JSON\",\r\n");
      out.write("\t\t\tasync\t\t: true,\r\n");
      out.write("\t\t\ttype\t\t: \"POST\",\r\n");
      out.write("\t\t\tdata\t\t: {},\r\n");
      out.write("\t\t\tsuccess\t\t: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tif(!crew.ajaxValidate(data)){ return; }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('#head').before(data.html);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tconsole.log(\"---------------------------------> error!!\");\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(jqXHR);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\tif (getCookie('mainEventPop') != \"close\") {\r\n");
      out.write("\t\t\t\t\tshowEventPop();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction mainTopBrnClose(obj) {\r\n");
      out.write("\t\t$(obj).closest('.ma_top_brn').addClass('close');\r\n");
      out.write("\t\tif(location.protocol == 'main.html'){\r\n");
      out.write("\t\t\tdocument.cookie = \"mainTopBrn=close; path=/;\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.cookie = \"mainTopBrn=close; path=/;SameSite=None; Secure;\";\r\n");
      out.write("\t\t\t//document.cookie = 'cross-site-cookie=bar; SameSite=None; Secure';\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction createPersonCpn(){\r\n");
      out.write("\t\t// 요청처리\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl\t\t\t: \"/pc/main/personCpn.json\",\r\n");
      out.write("\t\t\tdataType\t: \"JSON\",\r\n");
      out.write("\t\t\tasync\t\t: true,\r\n");
      out.write("\t\t\ttype\t\t: \"POST\",\r\n");
      out.write("\t\t\tdata\t\t: {},\r\n");
      out.write("\t\t\tsuccess\t\t: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tif(!crew.ajaxValidate(data)){ return; }\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 데이터 채우기\r\n");
      out.write("\t\t\t\tif(data.personCpnYn == \"Y\"){\r\n");
      out.write("\t\t\t\t\t$(\".mbrCpnNoDataArea\").hide();\r\n");
      out.write("\t\t\t\t\t$(\".mbrCpnListArea\").find(\".dataListArea\").html(data.html);\r\n");
      out.write("\t\t\t\t\t$(\".mbrCpnListArea\").find(\".count_wrap\").html('<span class=\"num\"><em>1</em>/'+data.listSize+'</span><span class=\"hide\">총 페이지 '+data.listSize+' 페이지 중 현재 1번째 페이지</span>').show();\r\n");
      out.write("\t\t\t\t\t$(\".mbrCpnListArea\").show();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvcui.require( ['ui/carousel'], function() {\r\n");
      out.write("\t\t\t\t\t\t// default: infinite loop sliding 루핑 슬라이드\r\n");
      out.write("\t\t\t\t\t\t$('.mbrCpnListArea .ui_carousel').vcCarousel();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsetTimeout(function () {\r\n");
      out.write("\t\t\t\t\t\tvar $wrap = $('.mbrCpnListArea');\r\n");
      out.write("\t\t\t\t\t\tvar $carousel = $wrap.find('.ui_carousel');\r\n");
      out.write("\t\t\t\t\t\t$carousel.on( 'carouselafterchange', function( evt, carousel ) {\r\n");
      out.write("\t\t\t\t\t\t\tvar index = carousel.currentSlide, $player;\r\n");
      out.write("\t                        var templateCount = '<strong>'+(index+1)+'</strong>/'+carousel.$slides.length;\r\n");
      out.write("\t                        $(carousel.el).find('.count_wrap>span.num').html( templateCount );\r\n");
      out.write("\r\n");
      out.write("\t                        if( ($player = carousel.$slides.eq(carousel.previousSlide).find('iframe')).length  ) {\r\n");
      out.write("\t                            var $wrap = $player.parent();\r\n");
      out.write("\t                            $player.remove();\r\n");
      out.write("\t                            $wrap.children().show();\r\n");
      out.write("\t                        }\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}, 100);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar firstDlvDt = data.firstDlvDt;\r\n");
      out.write("\t\t\t\t\t$(\".mbrCpnNoDataArea\").find(\"strong\").html(firstDlvDt.dlUnstScheMonth + \"월 \" + firstDlvDt.dlUnstScheDay + \"일(\" + firstDlvDt.dlUnstScheWeekNm + \")에 받을 수 있어요\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar firstDlvTime = data.firstDlvTime;\r\n");
      out.write("\t\t\t\t\tvar setOdrEndTimer = function (){\r\n");
      out.write("\t\t\t\t\t\t// 시, 분, 초 계산\r\n");
      out.write("\t\t\t\t\t\tvar hour\t= Math.floor(firstDlvTime / 1000 / 60 / 60);\r\n");
      out.write("\t\t\t\t\t\tvar min\t\t= Math.floor((firstDlvTime - (hour * 1000 * 60 * 60)) / 1000 / 60);\r\n");
      out.write("\t\t\t\t\t\tvar sec\t\t= Math.floor((firstDlvTime - (hour * 1000 * 60 * 60) - (min * 1000 * 60)) / 1000);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\".mbrCpnNoDataArea\").find(\".link_time>span\").html((hour < 10 ? \"0\" + hour : hour) + \":\" + (min < 10 ? \"0\" + min : min) + \":\" + (sec < 10 ? \"0\" + sec : sec));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 1초 차감\r\n");
      out.write("\t\t\t\t\t\tfirstDlvTime = firstDlvTime - 1000;\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(setOdrEndTimer, 1000);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tsetOdrEndTimer();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tconsole.log(\"---------------------------------> error!!\");\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(jqXHR);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t// 개인화 영역(주문) 구성 처리\r\n");
      out.write("\tfunction createPersonOrder(){\r\n");
      out.write("\t\t// 요청처리\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl\t\t\t: \"/pc/main/personOrder.json\",\r\n");
      out.write("\t\t\tdataType\t: \"JSON\",\r\n");
      out.write("\t\t\tasync\t\t: true,\r\n");
      out.write("\t\t\ttype\t\t: \"POST\",\r\n");
      out.write("\t\t\tdata\t\t: {},\r\n");
      out.write("\t\t\tsuccess\t\t: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tif(!crew.ajaxValidate(data)){ return; }\r\n");
      out.write("\r\n");
      out.write("// \t\t\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 데이터 채우기\r\n");
      out.write("\t\t\t\tif(data.personOrderYn == \"Y\"){\r\n");
      out.write("\t\t\t\t\t$(\".mbrOrderNoDataArea\").hide();\r\n");
      out.write("\t\t\t\t\t$(\".mbrOrderListArea>div.login_delivery\").html(data.html);\r\n");
      out.write("\t\t\t\t\t$(\".mbrOrderListArea\").show();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(!cj.isEmpty('')) {\r\n");
      out.write("\t\t\t\t\t// 파라미터가 있으면 해당 클래스의 위치로 스크롤 이동\r\n");
      out.write("\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\tscrollToClass();\r\n");
      out.write("\t\t\t\t\t}, 100);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tconsole.log(\"---------------------------------> error!!\");\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(jqXHR);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 신메뉴 알림 클릭시\r\n");
      out.write("\tfunction goNewNoticeManage(toggle){\r\n");
      out.write("\t\tif(cjConf.loginYn != \"Y\"){\r\n");
      out.write("\t\t\tif(!confirm(\"로그인이 필요한 서비스입니다.\\n로그인하시겠습니까?\")) return;\r\n");
      out.write("\t\t\tcj.login();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(toggle == 'on'){\r\n");
      out.write("\t\t\tif(!confirm(\"신메뉴 알림을 취소하시겠습니까?\")) return false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(!confirm(\"신메뉴 알림을 설정하시겠습니까?\")) return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tlocation.href=\"https://www.cjcookit.com/pc/myOrder/newNoticeManage\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 이벤트 팝업 보기\r\n");
      out.write("\tfunction showEventPop() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\tasync: true,\r\n");
      out.write("\t\t\turl: '/pc/main/getEventPopList.json',\r\n");
      out.write("\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\ttype: 'POST',\r\n");
      out.write("\t\t\tsuccess: function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\t// 로그인 실패 메세지 처리\r\n");
      out.write("\t\t\t\tif (!crew.ajaxValidate(data)) {\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#mainEventPop\").remove();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\".modal-container\").append(data.html);\r\n");
      out.write("\t\t\t\t/* vcui.require( ['ui/modal'], function() {\r\n");
      out.write("\t\t\t\t\t$(\"#mainEventPop\").vcModal();\r\n");
      out.write("\t        \t});\r\n");
      out.write(" */\r\n");
      out.write(" \t\t\t\tif($(\"#mainEventPop\")){\r\n");
      out.write(" \t\t\t\t\t$(\"#mainEventPop\").show();\t\r\n");
      out.write(" \t\t\t\t\t$('article.main_ev').css('top',parseInt($(\".pro_module\").eq(0).offset().top));\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\tvcui.require( ['ui/carousel'], function() {\r\n");
      out.write("\t\t\t\t\t// default: infinite loop sliding 루핑 슬라이드\r\n");
      out.write("\t\t\t\t\t$('#mainEventPop .ui_carousel').vcCarousel();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t//console.log(jqXHR.status);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 이벤트 팝업 오늘 하루 보지 않기\r\n");
      out.write("\tfunction closeEventPopToday() {\r\n");
      out.write("\t\tvar todayDate = new Date();\r\n");
      out.write("\t\ttodayDate = new Date(parseInt(todayDate.getTime() / 86400000) * 86400000 + 54000000);\r\n");
      out.write("\t\tvar expiredays = 1;\r\n");
      out.write("\t\tif ( todayDate > new Date() ) {\r\n");
      out.write("\t\t\texpiredays = expiredays - 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttodayDate.setDate(todayDate.getDate() + expiredays);\r\n");
      out.write("\t\tif(location.protocol == 'main.html'){\r\n");
      out.write("\t\t\tdocument.cookie = \"mainEventPop=close; path=/; expires=\" + todayDate.toGMTString() + \";\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.cookie = \"mainEventPop=close; path=/;SameSite=None; Secure; expires=\" + todayDate.toGMTString() + \";\";\r\n");
      out.write("\t\t\t//document.cookie = 'cross-site-cookie=bar; SameSite=None; Secure';\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t$('.ui_modal_wrap').remove();\r\n");
      out.write("\t\t$(\"#closeEventPopBtn\").trigger(\"click\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction closeEventPopup(){\r\n");
      out.write("\t\t$('.ui_modal_wrap').remove();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//재판매알림신청시 버튼 활성화처리\r\n");
      out.write("\tfunction resaleReqAfterCallback(obj) {\r\n");
      out.write("\t\tvar txt = obj.find('span.hide');\r\n");
      out.write("\t\tobj.addClass(\"on\");\r\n");
      out.write("\t\ttxt.text(\"재판매 알림 신청 완료\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//재판매알림신청취소시 버튼 비활성화처리\r\n");
      out.write("\tfunction resaleCancelAfterCallback(obj) {\r\n");
      out.write("\t\tvar txt = obj.find('span.hide');\r\n");
      out.write("\t\tobj.removeClass(\"on\");\r\n");
      out.write("\t\ttxt.text(\"재판매 알림 신청\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 맛취향 개인화 설정\r\n");
      out.write("\tfunction setFlvrTst(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl\t\t\t: \"/pc/main/getMemberFlvrTstCd.json\",\r\n");
      out.write("\t\t\tdataType\t: \"JSON\",\r\n");
      out.write("\t\t\tasync\t\t: true,\r\n");
      out.write("\t\t\ttype\t\t: \"POST\",\r\n");
      out.write("\t\t\tdata\t\t: {},\r\n");
      out.write("\t\t\tsuccess\t\t: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tif(!crew.ajaxValidate(data)){ return; }\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\".ma_individ .sl_taste a[flvrTstCd='\"+data.flvrTstCd+\"']\").trigger(\"click\");\r\n");
      out.write("\t\t\t\tchangeRecom();\r\n");
      out.write("\t\t\t\t$(\".ma_individ .desc .name\").text(data.mbrNm+\"님\");\r\n");
      out.write("\t\t\t\t$(\".personProdCase\"+data.personProdCase).show();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tconsole.log(\"---------------------------------> error!!\");\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(jqXHR);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 스크롤 해당 클래스 엘리먼트 위치로 이동\r\n");
      out.write("\tfunction scrollToClass() {\r\n");
      out.write("\t\tvar offsetClass = '.';\r\n");
      out.write("\t\tif($(offsetClass).length == 0) { return; }\r\n");
      out.write("\t\t$(window).scrollTop($(offsetClass).offset().top);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeRecom(){\r\n");
      out.write("\t\tsetTimeout(function () {\r\n");
      out.write("\t\t\t$(\"#personProdArea .list_recom:visible\").find(\"img[data-image_src]\").each(function(){\r\n");
      out.write("\t\t\t\tvar imageSrc = $(this).data(\"image_src\");\r\n");
      out.write("\t\t\t\tif(!cj.isEmpty(imageSrc)){\r\n");
      out.write("\t\t\t\t\t$(this).prop(\"src\", imageSrc).data(\"image_src\", \"\");\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}, 0);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- //content -->\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 챗봇 레이어 팝업 -->\r\n");
      out.write("<article class=\"lay_chatbot_wrap_ok\">\r\n");
      out.write("    <!-- <div class=\"lay_chatbot_frame\">\r\n");
      out.write("        <section class=\"chatbot_conts\">\r\n");
      out.write("          <iframe src=\"about:blank\" id=\"iframeChatbot\" allow=\"geolocation\"></iframe>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div class=\"close\">\r\n");
      out.write("            <button type=\"button\" class=\"btn_chatbot_close\"><span class=\"hide\">닫기</span></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("    <!-- 레이어 팝업 -->\r\n");
      out.write("    <article class=\"lay_wrap_chatbot modal_chatbot\" style=\"display:none;\">\r\n");
      out.write("        <h1 class=\"hide\"><span class=\"hide\">앱업데이트안내(필수)</span></h1>\r\n");
      out.write("        <section class=\"lay_conts\">\r\n");
      out.write("            <!-- 190419_구조 수정 -->\r\n");
      out.write("            <div class=\"laypop_cont\">\r\n");
      out.write("                <p>챗봇 창을 닫으시면, <br>기존 채팅 내용이 초기화됩니다.<br>챗봇 창을 닫으시겠습니까?</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //190419_구조 수정 -->\r\n");
      out.write("            <div class=\"btn_wrap laypop\">\r\n");
      out.write("                <button type=\"button\" class=\"btn_lay_chatbot ui_closeCancel\">취소</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn_lay_chatbot green ui_closeConfirm\">확인</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </article>\r\n");
      out.write("    <div class=\"dimmed\" style=\"display:none;\"></div>\r\n");
      out.write("</article>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    /*!\r\n");
      out.write("        Chatbot Layer, open/close \r\n");
      out.write("    */\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("        var $floatingWrap = $('.fix_contsbtm');\r\n");
      out.write("        var $chatbotWrap = $('.lay_chatbot_wrap_ok');\r\n");
      out.write("        var $chatbotFrame = $chatbotWrap.find('.lay_chatbot_frame');\r\n");
      out.write("        \r\n");
      out.write("        $floatingWrap.on( 'click', 'button.chatbot', function() {\r\n");
      out.write("        \tconsole.log(\"1\");\r\n");
      out.write("            openChatbot( true ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        $chatbotWrap.on( 'click', 'button.btn_chatbot_close', function() {\r\n");
      out.write("            openModalAlert( true ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        $chatbotWrap.on( 'click', 'button.ui_closeCancel', function() {\r\n");
      out.write("            openModalAlert( false ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        $chatbotWrap.on( 'click', 'button.ui_closeConfirm', function() {\r\n");
      out.write("            openModalAlert( false ); \r\n");
      out.write("            openChatbot( false ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        function openModalAlert( open ) { \r\n");
      out.write("            var state = open ? 'show' : 'hide'; \r\n");
      out.write("            $chatbotWrap.find('.dimmed')[state](); \r\n");
      out.write("            $chatbotWrap.find('.modal_chatbot')[state](); \r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        function openChatbot( open ) { \r\n");
      out.write("            if( open ) {\r\n");
      out.write("                $chatbotWrap.show(); \r\n");
      out.write("                $chatbotFrame.animate( {top:0}, 460, 'easeOutCubic' ); \r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("                $chatbotFrame.animate( {top:640}, 400, 'easeInCubic', function() {\r\n");
      out.write("                    $chatbotWrap.hide(); \r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<div class=\"footer_loca\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"fix_contsbtm\"> <!-- 스크립트요청사항 : 바닥컨텐츠가 .btm 클래스 추가해주세요 -->\r\n");
      out.write("    <div class=\"fx_button chatbot ui_chatBot show\">\r\n");
      out.write("<!--         <button type=\"button\" class=\"chatbot\" onclick=\"javascript:cj.chatbot.open('http://cookit.oli-va.com/');\">\r\n");
      out.write("            <span class=\"hide\">챗봇으로 문의하기</span>\r\n");
      out.write("        </button> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"fx_button top ui_gotoTop show\">\r\n");
      out.write("        <a href=\"#wrap\" role=\"button\">\r\n");
      out.write("            <span class=\"hide\">페이지 상단으로</span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function toggleUiFamilyArea(obj) {\r\n");
      out.write("\tvar _this = $(obj);\r\n");
      out.write("\t_this.closest('.ui_familySite').toggleClass('on');\r\n");
      out.write("\t_this.closest('.ui_familySite').find('.ly_manage').toggleClass('show');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"modal-container\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(evt){\r\n");
      out.write("\t//카카오 JavaScript 키 설정\r\n");
      out.write("\tKakao.init('44db3bbd3ed2c23cfd950c7ac71aee25');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../cjkit/web/js/vcui17e0.js?20200924090026\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../cjkit/web/js/olivekitchen.site17e0.js?20200924090026\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//vcui.require.config( {baseUrl:'http://publish.cjcookit.com/cjkit/mobile/js'} );\r\n");
      out.write("\tvcui.require.config( {baseUrl:'//www.cjcookit.com/cjkit/web/js'} );\r\n");
      out.write("\t//olivekitchen._.addon.carousel = false;\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.lazy.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function setIframe(target , link , description)\r\n");
      out.write("{\r\n");
      out.write("   var demo_Iframe = document.createElement(\"iframe\");\r\n");
      out.write("   demo_Iframe.src = \"/pc/footer/cookitInsta?mid1=\"+target;\r\n");
      out.write("   demo_Iframe.id=\"demo_Iframe\";\r\n");
      out.write("   demo_Iframe.width=\"0\";\r\n");
      out.write("   demo_Iframe.height=\"0\";\r\n");
      out.write("   document.getElementsByTagName('body')[0].appendChild(demo_Iframe);\r\n");
      out.write("   if(!cj.isEmpty(link)) cj.go.outLinkOpen(link, 'Y');  \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tolivekitchen._.addon.carousel = false;\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tvcui.require(['cookit/main'], function() {\r\n");
      out.write("\t\t        $('#wrap').vcMain();\r\n");
      out.write("\t\t        initMain();\r\n");
      out.write("\r\n");
      out.write("\t\t        /* 190710_웹접근성 */\r\n");
      out.write("\t\t        $.each( $('.ma_billboard').find('li.slide_conts'), function( i, item ) {\r\n");
      out.write("\t\t            $(item).find('.img_wrap > a').attr('tabindex',0);\r\n");
      out.write("\r\n");
      out.write("\t\t            if( $(item).hasClass('ui_carousel_cloned') ) {\r\n");
      out.write("\t\t                $(item).find('a, input, button, select').attr('tabindex',-1);\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t        /* //190710_웹접근성 */\r\n");
      out.write("\t\t    });\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar params = {};//파라미터 없음\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: '/pc/myFpn/fpnViewMenu',\r\n");
      out.write("\t\tdataType: 'json',\r\n");
      out.write("\t\ttype: 'POST',\r\n");
      out.write("\t\tdata: params,\r\n");
      out.write("\t\tsuccess: function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\tif(data.fpnData != null) {\r\n");
      out.write("\t\t\t\t$('#fpnMenuView').show();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('#fpnMenuView').hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\tconsole.log(jqXHR.status);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/makePCookie.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"jehu-container\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tsetTimeout(function () {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\tasync\t\t: true,\r\n");
      out.write("\t\t\turl\t\t\t: '/pc/comm/jehuScript.json',\r\n");
      out.write("\t\t\tdataType\t: 'json',\r\n");
      out.write("\t\t\ttype\t\t: 'POST',\r\n");
      out.write("\t\t\tdata\t\t: { requestUri : '/pc/main' },\r\n");
      out.write("\t\t\tsuccess\t\t: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\tif(!crew.ajaxValidate(data)){ return; }\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t$(\".jehu-container\").append(data.html);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror\t   : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t  //console.log(jqXHR.status);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}, 1000);\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.cjcookit.com/pc/main by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Mar 2021 09:53:46 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
