/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-30 06:24:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.member.db.MemberBean;
import com.recipe.board.db.RecipeBean;
import java.util.List;

public final class menuList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.member.db.MemberBean");
    _jspx_imports_classes.add("com.recipe.board.db.RecipeBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.cjcookit.com/pc/menu/menuList by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Mar 2021 09:53:58 GMT -->\r\n");
      out.write("<!-- Added by HTTrack --><meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" /><!-- /Added by HTTrack -->\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\t\t<title>COOKIT 메뉴</title>\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"https://www.cjcookit.com/cjkit/web/images/favicon.ico\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/common.css?20200924090025\">\r\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/chatbot.css?20200924090025\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/pd.css?20200924090025\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/op.css?20200924090025\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/recipeCSS/menuList.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\t\t<div id=\"skipnavi\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#container_title\">본문바로가기</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"preloader\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"loader\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"loading\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- header -->\r\n");
      out.write("\t\t ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- //header -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");

			//request영역에서 꺼내기
			List recipeList = (List)request.getAttribute("recipeList");
			
			String f_mem_id = (String)session.getAttribute("f_mem_id");
			String f_mem_nick = (String)session.getAttribute("f_mem_nick");
			
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<section id=\"container\" >\r\n");
      out.write("\t\t\t\t\t<div id=\"container_title\" class=\"hide\" tabindex=\"-1\">본문 시작</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- content -->\r\n");
      out.write("\t\t<div id=\"content\" class=\"pd_wrap\">\r\n");
      out.write("\t\t\t<div class=\"olki_list_wrap\">\r\n");
      out.write("\t\t\t\t<div class=\"top_sec\">\r\n");
      out.write("\t\t\t\t<h2> COOKIT 레시피</h2>\r\n");
      out.write("\t\t\t\t<!-- 팀프로젝트 코드 들어가는 부분 본문 -->\r\n");
      out.write("\t\t\t\t<div class=\"cate_wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tab_wrap\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectDate on\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>전체보기</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>국·탕</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>볶음·반찬</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>분식</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>간식·디저트</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>술이한잔</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>캠핑·여행</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>고기류</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>해물류</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"tabSelect tabSelectTheme\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"./RecipeList.re?item=9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>헬씨·다이어트</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-------------- 글쓰기 --------------->\r\n");
      out.write("\t\t\t\t");
 if(f_mem_id != null){
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t<div class=\"writebutton\">\r\n");
      out.write("\t\t\t\t\t\t\t<button onclick=\"location.href='./RecipeWrite.re'\">\r\n");
      out.write("\t\t\t\t\t\t\t<img title=\"글쓰기\" src=\"./cjkit/web/images/recipeIcon/writeicon.png\" width=\"50px;\" height=\"50px;\"></button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t<!-------------- 글쓰기 ------------>\r\n");
      out.write("\t\t\t\t");

				String item = request.getParameter("item"); 
				if("null".equals(item)){
					item = "all";
				}
				
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<!--- 상품 정렬 최신순/조회순 --->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<form action=\"./RecipeList.re?item=");
      out.print(item );
      out.write("\" name=\"form\" method=\"get\" style=\"float:right;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"item\" value=\"");
      out.print(item );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"type\" class=\"sele\" onchange=\"sel(); \">\t\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"newest\" \r\n");
      out.write("\t\t\t\t\t\t\t");
 
							String type = request.getParameter("type");
								if(type != null){
									if(type.equals("newest")){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tselected\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
								}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t>최신순</option>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hit\"\r\n");
      out.write("\t\t\t\t\t\t\t");

								if(type != null){
									if(type.equals("hit")){
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tselected\r\n");
      out.write("\t\t\t\t\t\t\t");

							}  }
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t>인기순</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\tfunction sel(){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.form.submit();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");

						//상품의 총 개수
						int size = 0;
						try{
							size = recipeList.size();
						}catch(Exception e){
							
						}
						/* int size = recipeList.size(); */
					    // 상품의 열의 개수 8개
					    int col = 4;
					    // 상품의 행의 개수
					    int row = (size / col) + (size % col>0? 1:0);
					    // 출력카운트
					    int num = 0;
						
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"olki_list prodListArea\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t");

						      for(int a=0;a<row;a++){
						    	  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 이미지케이스 -->\r\n");
      out.write("\t\t\t\t\t\t    \t  ");
 for(int b=0;b<col;b++){
						    		  RecipeBean rb = (RecipeBean) recipeList.get(num);
						    	  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"item\" style=\"height: 541px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pro_module\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"./RecipeDetail.re?f_rcp_num=");
      out.print(rb.getF_rcp_num());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"./recipe_upload/");
      out.print(rb.getF_rcp_th_img());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"txt_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"\" class=\"conts\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"etc_info\">\r\n");
      out.write("\t\t                    \t<span class=\"txt\">\r\n");
      out.write("\t\t                    \t\t");
      out.write('#');
      out.print(rb.getF_rcp_hashtag() );
      out.write("<!-- </a> -->\r\n");
      out.write("\t\t                    \t</span>\r\n");
      out.write("\t\t            \t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tit_info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"tit mt_elps\">");
      out.print(rb.getF_rcp_title() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"nick_info\">");
      out.print(rb.getF_rcp_nick() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"view_count\">조회수 ");
      out.print(rb.getF_rcp_count() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

				    		num++;
				    		if(size<=num) break;
				    	  	}
				    	 	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- //이미지케이스 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- /////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\t\t\t\t<!-- 팀프로젝트 코드 들어가는 부분 본문  끝-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 챗봇 레이어 팝업 -->\r\n");
      out.write("\t\t<article class=\"lay_chatbot_wrap_ok\">\r\n");
      out.write("\t\t    <div class=\"lay_chatbot_frame\">\r\n");
      out.write("\t\t        <section class=\"chatbot_conts\">\r\n");
      out.write("\t\t          <iframe src=\"about:blank\" id=\"iframeChatbot\" allow=\"geolocation\"></iframe>\r\n");
      out.write("\t\t        </section>\r\n");
      out.write("\t\t        <div class=\"close\">\r\n");
      out.write("\t\t            <button type=\"button\" class=\"btn_chatbot_close\"><span class=\"hide\">닫기</span></button>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <!-- 레이어 팝업 -->\r\n");
      out.write("\t\t    <article class=\"lay_wrap_chatbot modal_chatbot\" style=\"display:none;\">\r\n");
      out.write("\t\t        <h1 class=\"hide\"><span class=\"hide\">앱업데이트안내(필수)</span></h1>\r\n");
      out.write("\t\t        <section class=\"lay_conts\">\r\n");
      out.write("\t\t            <!-- 190419_구조 수정 -->\r\n");
      out.write("\t\t            <div class=\"laypop_cont\">\r\n");
      out.write("\t\t                <p>챗봇 창을 닫으시면, <br>기존 채팅 내용이 초기화됩니다.<br>챗봇 창을 닫으시겠습니까?</p>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            <!-- //190419_구조 수정 -->\r\n");
      out.write("\t\t            <div class=\"btn_wrap laypop\">\r\n");
      out.write("\t\t                <button type=\"button\" class=\"btn_lay_chatbot ui_closeCancel\">취소</button>\r\n");
      out.write("\t\t                <button type=\"button\" class=\"btn_lay_chatbot green ui_closeConfirm\">확인</button>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t        </section>\r\n");
      out.write("\t\t    </article>\r\n");
      out.write("\t\t    <div class=\"dimmed\" style=\"display:none;\"></div>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<!-- //Footer -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Mirrored from www.cjcookit.com/pc/menu/menuList by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Mar 2021 09:54:00 GMT -->\r\n");
      out.write("\t\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
