/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-30 06:25:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goodRes_005freview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.review.db.ReviewBean;
import java.util.List;

public final class gr_005frvMy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.review.db.ReviewBean");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.cjcookit.com/pc/event/eventMain by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Mar 2021 09:53:50 GMT -->\r\n");
      out.write("<!-- Added by HTTrack --><meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" /><!-- /Added by HTTrack -->\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 팀프로젝트와 관련 없는  코드입니다. 건드리지 말것....(시작) -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>라따뚜이</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"https://www.cjcookit.com/cjkit/web/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/common.css?20200924090025\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/chatbot.css?20200924090025\">\r\n");
      out.write("\t<!-- uri array -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 업무 단위로 c:when 문 추가하여 사용하세요. -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/ev.css?20200924090025\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/stamp.css?20200924090025\"> <!-- 20200130_추가 -->\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/my.css?20200924090025\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../cjkit/web/js/libs/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar cjConf = {\r\n");
      out.write("\t\t\tserverImg : \"//www.cjcookit.com/cjkit/web/images\",\r\n");
      out.write("\t\t\tloginYn : \"N\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery/jquery.form.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/crew/crew17e0.js?20200924090026\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/crew/form/form17e0.js?20200924090026\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/cj17e0.js?20200924090026\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/oauth/kakao.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/oauth/naveridlogin_js_sdk_2.0.0.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.cjcookit.com/pc/js/netfunnel.js?20200924090026\" charset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://www.cjcookit.com/pc/js/om_pc_skin.js?20200924090026\" charset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/webtoolkit.base64.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://nsso.cjone.com/findCookieSecured.jsp?cjssoq=fOYjm2%2FlJbWuG7If5njx%2FuF8RRF9w4%2BkbMBBqJUhojnBiyY0JLSJBB0HC0q3lSH8O2PzVFZdZMVBknu0V9WGuVBoR2p5QmJxdHlSbjlwR0JOWWNiWlFJcU1hMDVPNWhhMldQdnZHc2k4Z1hkRGlGSkE4YXU1bkw0RFFtYklSYTVzdUNkNldCaTZSVT0%3D\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t//$(document).ready(function(evt){\r\n");
      out.write("\t\t\tif((typeof _cjssoEncData) != \"undefined\" && _cjssoEncData !=\"\"){\r\n");
      out.write("\t\t\t\tvar redirectUrl = location.pathname + location.search;\r\n");
      out.write("\t\t\t\tvar data = {};\r\n");
      out.write("\t\t\t\tdata.redirectUrl\t\t= redirectUrl;\r\n");
      out.write("\t\t\t\tdata.mode\t\t\t= \"SSO_AUTH\";\r\n");
      out.write("\t\t\t\tdata.cjssoq\t\t\t= _cjssoEncData;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 전송\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\tasync\t\t: true,\r\n");
      out.write("\t\t\t\t\turl\t\t\t: '/pc/auth/login.json',\r\n");
      out.write("\t\t\t\t\tdataType\t: 'json',\r\n");
      out.write("\t\t\t\t\ttype\t\t: 'POST',\r\n");
      out.write("\t\t\t\t\tdata\t\t: data,\r\n");
      out.write("\t\t\t\t\tsuccess\t\t: function(data, textStatus, jqXHR){\r\n");
      out.write("\t\t\t\t\t\t// 로그인 처리 결과 체크\r\n");
      out.write("\t\t\t\t\t\tcj.loginResultCheck(data);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror\t   : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t  //console.log(jqXHR.status);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//});\r\n");
      out.write("\t\t</script>\t\r\n");
      out.write("\t<meta name=\"google-site-verification\" content=\"0GuzYD2oaBVARveIoOEQEEx10478h5Vnn5i5YNAS6zI\" />\t \r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar _isFlagContinue= false;\r\n");
      out.write("\t\t\tfunction fn_evntAgreePop(evntId){\r\n");
      out.write("\t\t\t\tvar params = {evntId: evntId};\r\n");
      out.write("\t\t\t\tif(_isFlagContinue) return false;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (cjConf.loginYn != 'Y') {\r\n");
      out.write("\t\t\t\t\talert('로그인 후 참여 하시기 바랍니다.');\r\n");
      out.write("\t\t\t\t\tcj.login();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t_isFlagContinue = true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 테스트 구문 퍼블 후 적용.\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\tasync: true,\r\n");
      out.write("\t\t\t\t\turl: \"/pc/event/eventAgree.json\",\r\n");
      out.write("\t\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\t\ttype: 'POST',\r\n");
      out.write("\t\t\t\t\tdata: params,\r\n");
      out.write("\t\t\t\t\tsuccess: function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\t\t\tif (!crew.ajaxValidate(data)) {\r\n");
      out.write("\t\t\t\t\t\t\t_isFlagContinue = false;\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif((data.html).length == 0){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"동의항목이 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t_isFlagContinue = false;\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#lay_wrap\").remove();\r\n");
      out.write("\t\t\t\t\t\t\t$(\".modal-container\").append(data.html);\r\n");
      out.write("\t\t\t\t\t\t\tvcui.require( ['ui/modal'], function() {\r\n");
      out.write("\t\t\t\t            \t$(\"#lay_wrap\").vcModal();\r\n");
      out.write("\t\t\t\t        \t});\r\n");
      out.write("\t\t\t\t\t\t\t_isFlagContinue = false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\t\t//console.log(jqXHR.status);\r\n");
      out.write("\t\t\t\t\t\t_isFlagContinue = false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t<!-- 팀프로젝트와 관련 없는  코드입니다. 건드리지 말것....(끝) -->\r\n");
      out.write("\t<!-- 팀프로젝트와 관련된 CSS 코드 링크를 여기서 부터 넣어주시면 됩니다. -->\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/common.css?20200924090025\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/reWriteCSS/gr_rvMy.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 팀프로젝트와 관련된 CSS 코드 링크를 여기서 부터 넣어주시면 됩니다.(끝) -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- header -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- //header -->\r\n");
      out.write("\t<!--(팀프로젝트 쇼핑몰 리스트) 여기서부터 본문 시작입니다. -->\r\n");
      out.write("\t");

		List myReviewList = (List) request.getAttribute("myReviewList");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"sec_review\">\r\n");
      out.write("\t\t<div><h1 class=\"h1_title\">내가 쓴 리뷰<h1><div>\r\n");
      out.write("\t\t<div class=\"div_review\">\r\n");
      out.write("\t\t\t");

				for (int i = 0; i < myReviewList.size(); i++) {
					ReviewBean rb = (ReviewBean) myReviewList.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"div_tab\">\r\n");
      out.write("\t\t\t\t<table class=\"tab_review\" border=\"1\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>id</th>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(rb.getF_grv_mem_id());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>star</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='star-rating'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"width: calc(");
      out.print(rb.getF_grv_star());
      out.write("*20%)\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						if (!rb.getF_grv_img().equals("")) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>image</th>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"./upload/");
      out.print(rb.getF_grv_img().split(",")[0]);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"130\" height=\"150\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						} else {
	
							}
					
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>content</th>\r\n");
      out.write("\t\t\t\t\t\t");

							String content = rb.getF_grv_content();
								if (content != null) {
									content = content.replace("\r\n", "<br>");
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(content);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"삭제하기\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='./ReviewDelete.rv?gr_num=");
      out.print(rb.getF_grv_gr_num());
      out.write("&grv_num=");
      out.print(rb.getF_grv_num());
      out.write("'\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"내 리뷰로 이동하기\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='./GoodResContentAction.gr?num=");
      out.print(rb.getF_grv_gr_num());
      out.write("'\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\t\r\n");
      out.write("\r\n");
      out.write("\t<!--(팀프로젝트 쇼핑몰 리스트) 여기서부터 본문 끝입니다. -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 팀프로젝트와 관련 없는  코드입니다. 건드리지 말것....(끝) -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#sorting_ev\").change(function() {\r\n");
      out.write("\t\t\t\tloadWinnerList(1);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar mode = \"\";\r\n");
      out.write("\t\t\tif (mode != \"\") {\r\n");
      out.write("\t\t\t\tgetListData(mode);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tloadEventLi\r\n");
      out.write("\t\t\t\tst();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 탭 이동\r\n");
      out.write("\t\tfunction getListData(type) {\r\n");
      out.write("\t\t\tif (type == \"EVENT\") {\r\n");
      out.write("\t\t\t\tif (!$(\".tabs > li:first\").hasClass(\"on\")) {\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:first\").addClass(\"on\");\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:last\").removeClass(\"on\");\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:first\").find(\"span\").append(\r\n");
      out.write("\t\t\t\t\t\t\t'<em class=\"hide\">선택됨</em>');\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:last\").find(\"span > em\").remove();\r\n");
      out.write("\t\t\t\t\t$(\".event_list\").show(); // 이벤트 목록 보이기 처리\r\n");
      out.write("\t\t\t\t\t$(\".img_left_wrap\").show(); // 이벤트 목록 슬라이드 보이기 처리\r\n");
      out.write("\t\t\t\t\t$(\".event_winner\").hide(); // 당첨자 발표 목록 숨김 처리\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tloadEventList(); // 이벤트 목록 조회\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tif (!$(\".tabs > li:last\").hasClass(\"on\")) {\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:last\").addClass(\"on\");\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:first\").removeClass(\"on\");\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:last\").find(\"span\").append(\r\n");
      out.write("\t\t\t\t\t\t\t'<em class=\"hide\">선택됨</em>');\r\n");
      out.write("\t\t\t\t\t$(\".tabs > li:first\").find(\"span > em\").remove();\r\n");
      out.write("\t\t\t\t\t$(\".event_list\").hide(); // 이벤트 목록 숨김 처리\r\n");
      out.write("\t\t\t\t\t$(\".img_left_wrap\").hide(); // 이벤트 목록 슬라이드 숨김 처리\r\n");
      out.write("\t\t\t\t\t$(\".event_winner\").show(); // 당첨자 발표 목록 보이기 처리\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tloadWinnerList(); // 당첨자 발표 목록 조회\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 이벤트 목록 데이터를 구성함.\r\n");
      out.write("\t\tvar isBlock = false;\r\n");
      out.write("\t\tfunction loadEventList(page) {\r\n");
      out.write("\t\t\t// block 처리\r\n");
      out.write("\t\t\tif (isBlock) {\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tisBlock = true;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (cj.isEmpty(page)) {\r\n");
      out.write("\t\t\t\tpage = 1;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(window).scrollTop($(\"#eventListArea\").offset().top - 50);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 전송\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync : true,\r\n");
      out.write("\t\t\t\turl : '/pc/event/eventList.json',\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tpage : page\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\t\tif (!crew.ajaxValidate(data)) {\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// html 적용\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#eventListArea\").html(data.html);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#eventPaging\").html(data.paging);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// block 해제\r\n");
      out.write("\t\t\t\t\tisBlock = false;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\tisBlock = false;\r\n");
      out.write("\t\t\t\t\t//console.log(jqXHR.status);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 당첨자 목록 데이터를 구성함.\r\n");
      out.write("\t\tvar isBlock2 = false;\r\n");
      out.write("\t\tfunction loadWinnerList(page) {\r\n");
      out.write("\t\t\t// block 처리\r\n");
      out.write("\t\t\tif (isBlock) {\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tisBlock2 = true;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 내가 참여한 이벤트 여부 확인\r\n");
      out.write("\t\t\tvar mbrSrcYn = \"\";\r\n");
      out.write("\t\t\tif ($(\"#sorting_ev\").prop(\"checked\")) {\r\n");
      out.write("\t\t\t\tvar isLogin = false;\r\n");
      out.write("\t\t\t\tif (!isLogin) {\r\n");
      out.write("\t\t\t\t\tif (confirm(\"로그인이 필요한 서비스입니다.\\n로그인 하시겠습니까?\")) {\r\n");
      out.write("\t\t\t\t\t\tcj.login();\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(\"#sorting_ev\").prop(\"checked\", false);\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tmbrSrcYn = \"Y\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tmbrSrcYn = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (cj.isEmpty(page)) {\r\n");
      out.write("\t\t\t\tpage = 1;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(window).scrollTop(\r\n");
      out.write("\t\t\t\t\t\t$(\"#winnerListArea > div:first\").offset().top);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 전송\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tasync : true,\r\n");
      out.write("\t\t\t\turl : '/pc/event/winnerList.json',\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tpage : page,\r\n");
      out.write("\t\t\t\t\tmbrSrcYn : mbrSrcYn\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\t\tif (!crew.ajaxValidate(data)) {\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// html 적용\r\n");
      out.write("\t\t\t\t\t$(\"#winnerListArea\").find(\".tb_row\").remove();\r\n");
      out.write("\t\t\t\t\t$(\"#winnerListArea\").find(\".no_data\").remove();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#winnerListArea > div:first\").after(data.html);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#winnerPaging\").html(data.paging);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// block 해제\r\n");
      out.write("\t\t\t\t\tisBlock2 = false;\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t\tisBlock2 = false;\r\n");
      out.write("\t\t\t\t\t//console.log(jqXHR.status);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 팀프로젝트와 관련 없는  코드입니다. 건드리지 말것....(끝) -->\r\n");
      out.write("\t<!-- //content -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 챗봇 레이어 팝업 -->\r\n");
      out.write("<!-- <article class=\"lay_chatbot_wrap_ok\">\r\n");
      out.write("    <div class=\"lay_chatbot_frame\">\r\n");
      out.write("        <section class=\"chatbot_conts\">\r\n");
      out.write("          <iframe src=\"about:blank\" id=\"iframeChatbot\" allow=\"geolocation\"></iframe>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div class=\"close\">\r\n");
      out.write("            <button type=\"button\" class=\"btn_chatbot_close\"><span class=\"hide\">닫기</span></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    레이어 팝업\r\n");
      out.write("    <article class=\"lay_wrap_chatbot modal_chatbot\" style=\"display:none;\">\r\n");
      out.write("        <h1 class=\"hide\"><span class=\"hide\">앱업데이트안내(필수)</span></h1>\r\n");
      out.write("        <section class=\"lay_conts\">\r\n");
      out.write("            190419_구조 수정\r\n");
      out.write("            <div class=\"laypop_cont\">\r\n");
      out.write("                <p>챗봇 창을 닫으시면, <br>기존 채팅 내용이 초기화됩니다.<br>챗봇 창을 닫으시겠습니까?</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            //190419_구조 수정\r\n");
      out.write("            <div class=\"btn_wrap laypop\">\r\n");
      out.write("                <button type=\"button\" class=\"btn_lay_chatbot ui_closeCancel\">취소</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn_lay_chatbot green ui_closeConfirm\">확인</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </article>\r\n");
      out.write("    <div class=\"dimmed\" style=\"display:none;\"></div>\r\n");
      out.write("</article> -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    /*!\r\n");
      out.write("        Chatbot Layer, open/close \r\n");
      out.write("    */\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("        var $floatingWrap = $('.fix_contsbtm');\r\n");
      out.write("        var $chatbotWrap = $('.lay_chatbot_wrap_ok');\r\n");
      out.write("        var $chatbotFrame = $chatbotWrap.find('.lay_chatbot_frame');\r\n");
      out.write("        \r\n");
      out.write("        $floatingWrap.on( 'click', 'button.chatbot', function() {\r\n");
      out.write("        \tconsole.log(\"1\");\r\n");
      out.write("            openChatbot( true ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        $chatbotWrap.on( 'click', 'button.btn_chatbot_close', function() {\r\n");
      out.write("            openModalAlert( true ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        $chatbotWrap.on( 'click', 'button.ui_closeCancel', function() {\r\n");
      out.write("            openModalAlert( false ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        $chatbotWrap.on( 'click', 'button.ui_closeConfirm', function() {\r\n");
      out.write("            openModalAlert( false ); \r\n");
      out.write("            openChatbot( false ); \r\n");
      out.write("        }); \r\n");
      out.write("\r\n");
      out.write("        function openModalAlert( open ) { \r\n");
      out.write("            var state = open ? 'show' : 'hide'; \r\n");
      out.write("            $chatbotWrap.find('.dimmed')[state](); \r\n");
      out.write("            $chatbotWrap.find('.modal_chatbot')[state](); \r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        function openChatbot( open ) { \r\n");
      out.write("            if( open ) {\r\n");
      out.write("                $chatbotWrap.show(); \r\n");
      out.write("                $chatbotFrame.animate( {top:0}, 460, 'easeOutCubic' ); \r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("                $chatbotFrame.animate( {top:640}, 400, 'easeInCubic', function() {\r\n");
      out.write("                    $chatbotWrap.hide(); \r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 팀프로젝트와 관련 없는  코드입니다. 건드리지 말것....(끝) -->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- //Footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- 팀프로젝트와 관련 없는  코드입니다. 건드리지 말것....(시작) -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- <div class=\"fix_contsbtm\">\r\n");
      out.write("\t\t스크립트요청사항 : 바닥컨텐츠가 .btm 클래스 추가해주세요\r\n");
      out.write("\t\t<div class=\"fx_button chatbot ui_chatBot show\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"chatbot\"\r\n");
      out.write("\t\t\t\tonclick=\"javascript:cj.chatbot.open('http://cookit.oli-va.com/');\">\r\n");
      out.write("\t\t\t\t<span class=\"hide\">챗봇으로 문의하기</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"fx_button top ui_gotoTop show\">\r\n");
      out.write("\t\t\t<a href=\"#wrap\" role=\"button\"> <span class=\"hide\">페이지 상단으로</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction toggleUiFamilyArea(obj) {\r\n");
      out.write("\t\t\tvar _this = $(obj);\r\n");
      out.write("\t\t\t_this.closest('.ui_familySite').toggleClass('on');\r\n");
      out.write("\t\t\t_this.closest('.ui_familySite').find('.ly_manage').toggleClass(\r\n");
      out.write("\t\t\t\t\t'show');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal-container\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function(evt) {\r\n");
      out.write("\t\t\t//카카오 JavaScript 키 설정\r\n");
      out.write("\t\t\tKakao.init('44db3bbd3ed2c23cfd950c7ac71aee25');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../../cjkit/web/js/vcui17e0.js?20200924090026\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../../cjkit/web/js/olivekitchen.site17e0.js?20200924090026\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t//vcui.require.config( {baseUrl:'http://publish.cjcookit.com/cjkit/mobile/js'} );\r\n");
      out.write("\t\tvcui.require.config({\r\n");
      out.write("\t\t\tbaseUrl : '//www.cjcookit.com/cjkit/web/js'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//olivekitchen._.addon.carousel = false;\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery/jquery.lazy.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction setIframe(target, link, description) {\r\n");
      out.write("\t\t\tvar demo_Iframe = document.createElement(\"iframe\");\r\n");
      out.write("\t\t\tdemo_Iframe.src = \"/pc/footer/cookitInsta?mid1=\" + target;\r\n");
      out.write("\t\t\tdemo_Iframe.id = \"demo_Iframe\";\r\n");
      out.write("\t\t\tdemo_Iframe.width = \"0\";\r\n");
      out.write("\t\t\tdemo_Iframe.height = \"0\";\r\n");
      out.write("\t\t\tdocument.getElementsByTagName('body')[0].appendChild(demo_Iframe);\r\n");
      out.write("\t\t\tif (!cj.isEmpty(link))\r\n");
      out.write("\t\t\t\tcj.go.outLinkOpen(link, 'Y');\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar params = {};//파라미터 없음\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/pc/myFpn/fpnViewMenu',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tdata : params,\r\n");
      out.write("\t\t\tsuccess : function(data, textStatus, jqXHR) {\r\n");
      out.write("\t\t\t\tif (data.fpnData != null) {\r\n");
      out.write("\t\t\t\t\t$('#fpnMenuView').show();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#fpnMenuView').hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tconsole.log(jqXHR.status);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/makePCookie.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 쿡킷 GA 스크립트 -->\r\n");
      out.write("\t<!-- Global site tag (gtag.js) - Google Analytics -->\r\n");
      out.write("\t<script async\r\n");
      out.write("\t\tsrc=\"http://www.googletagmanager.com/gtag/js?id=UA-142134398-1\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\twindow.dataLayer = window.dataLayer || [];\r\n");
      out.write("\t\tfunction gtag() {\r\n");
      out.write("\t\t\tdataLayer.push(arguments);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgtag('js', new Date());\r\n");
      out.write("\t\tgtag('config', 'UA-142134398-1');\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- e:쿡킷 GA 스크립트 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ADN M바로가기 리마케팅 start -->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar adn_quicklink_param = adn_quicklink_param || [];\r\n");
      out.write("\t\tadn_quicklink_param.push([ {\r\n");
      out.write("\t\t\tui : '102326',\r\n");
      out.write("\t\t\tci : '1023260001',\r\n");
      out.write("\t\t\tgi : '28018'\r\n");
      out.write("\t\t} ]);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../../../fin.rainbownine.net/js/adn_shortcut_remarketing_1.0.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ADN M바로가기 리마케팅 설치 end -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ADN Tracker[공통] start -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar adn_param = adn_param || [];\r\n");
      out.write("\t\tadn_param.push([ {\r\n");
      out.write("\t\t\tui : '101740',\r\n");
      out.write("\t\t\tut : 'Home'\r\n");
      out.write("\t\t} ]);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\" defer=\"\"\r\n");
      out.write("\t\tsrc=\"../../../fin.rainbownine.net/js/adn_tags_2.1.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ADN Tracker[공통] end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- FACEBOOK WEB SDK 실적 공통 적용  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t!function(f, b, e, v, n, t, s) {\r\n");
      out.write("\t\t\tif (f.fbq)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tn = f.fbq = function() {\r\n");
      out.write("\t\t\t\tn.callMethod ? n.callMethod.apply(n, arguments) : n.queue\r\n");
      out.write("\t\t\t\t\t\t.push(arguments)\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tif (!f._fbq)\r\n");
      out.write("\t\t\t\tf._fbq = n;\r\n");
      out.write("\t\t\tn.push = n;\r\n");
      out.write("\t\t\tn.loaded = !0;\r\n");
      out.write("\t\t\tn.version = '2.0';\r\n");
      out.write("\t\t\tn.queue = [];\r\n");
      out.write("\t\t\tt = b.createElement(e);\r\n");
      out.write("\t\t\tt.async = !0;\r\n");
      out.write("\t\t\tt.src = v;\r\n");
      out.write("\t\t\ts = b.getElementsByTagName(e)[0];\r\n");
      out.write("\t\t\ts.parentNode.insertBefore(t, s)\r\n");
      out.write("\t\t}(window, document, 'script',\r\n");
      out.write("\t\t\t\t'../../../connect.facebook.net/en_US/fbevents.js');\r\n");
      out.write("\t\tfbq('init', '429975664402063');\r\n");
      out.write("\t\tfbq('track', 'PageView');\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 모비온 Enliple Tracker Start -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t(function(a, g, e, n, t) {\r\n");
      out.write("\t\t\ta.enp = a.enp || function() {\r\n");
      out.write("\t\t\t\t(a.enp.q = a.enp.q || []).push(arguments)\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tn = g.createElement(e);\r\n");
      out.write("\t\t\tn.defer = !0;\r\n");
      out.write("\t\t\tn.src = \"../../../cdn.megadata.co.kr/dist/prod/enp_tracker_self_hosted.min.js\";\r\n");
      out.write("\t\t\tt = g.getElementsByTagName(e)[0];\r\n");
      out.write("\t\t\tt.parentNode.insertBefore(n, t)\r\n");
      out.write("\t\t})(window, document, \"script\");\r\n");
      out.write("\t\tenp('create', 'common', 'cjcookit', {\r\n");
      out.write("\t\t\tdevice : 'B'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tenp('send', 'common', 'cjcookit');\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- 모비온 Enliple Tracker End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 네이버 모바일 - 공통 적용 스크립트 , 모든 페이지에 노출되도록 설치. 단 전환페이지 설정값보다 항상 하단에 위치해야함 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../wcs.naver.net/wcslog.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tif (!wcs_add)\r\n");
      out.write("\t\t\tvar wcs_add = {};\r\n");
      out.write("\t\twcs_add[\"wa\"] = \"s_15f84e946d7d\";\r\n");
      out.write("\t\tif (!_nasa)\r\n");
      out.write("\t\t\tvar _nasa = {};\r\n");
      out.write("\t\twcs.inflow();\r\n");
      out.write("\t\twcs_do(_nasa);\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Global site tag (gtag.js) - Google Ads: 738287366 -->\r\n");
      out.write("\t<script async\r\n");
      out.write("\t\tsrc=\"http://www.googletagmanager.com/gtag/js?id=AW-738287366\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\twindow.dataLayer = window.dataLayer || [];\r\n");
      out.write("\t\tfunction gtag() {\r\n");
      out.write("\t\t\tdataLayer.push(arguments);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgtag('js', new Date());\r\n");
      out.write("\t\tgtag('config', 'AW-738287366');\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- WIDERPLANET  SCRIPT START 2020.7.7 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wp_tg_cts\" style=\"display: none;\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar wptg_tagscript_vars = wptg_tagscript_vars || [];\r\n");
      out.write("\t\twptg_tagscript_vars.push((function() {\r\n");
      out.write("\t\t\treturn {\r\n");
      out.write("\t\t\t\twp_hcuid : \"\", /*고객넘버 등 Unique ID (ex. 로그인  ID, 고객넘버 등 )를 암호화하여 대입.\r\n");
      out.write("\t\t\t\t *주의 : 로그인 하지 않은 사용자는 어떠한 값도 대입하지 않습니다.*/\r\n");
      out.write("\t\t\t\tti : \"49612\", /*광고주 코드 */\r\n");
      out.write("\t\t\t\tty : \"Home\", /*트래킹태그 타입 */\r\n");
      out.write("\t\t\t\tdevice : \"web\" /*디바이스 종류  (web 또는  mobile)*/\r\n");
      out.write("\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t}));\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\" async\r\n");
      out.write("\t\tsrc=\"../../../cdn-aitg.widerplanet.com/js/wp_astg_4.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- // WIDERPLANET  SCRIPT END 2020.7.7 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 팀프로젝트와 관련 없는  코드입니다. 건드리지 말것....(끝) -->\r\n");
      out.write("\t<!-- 팀프로젝트와 관련된 JS파일 넣는 경로 입니다. (시작)  -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 팀프로젝트와 관련된 JS파일 넣는 경로 입니다. (끝)  -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
