/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-31 11:27:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.recipe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RecipeWriteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<title>레시피 등록 - 집밥을 특별하게, 쿡킷</title>\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"https://www.cjcookit.com/cjkit/web/images/favicon.ico\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/common.css?20200924090025\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/main.css?20200924090025\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/recipeCSS/recipeWrite.css\">\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-3.5.1.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* 요리 순서 이미지 생성 */\r\n");
      out.write("\t \r\n");
      out.write("\tvar sel_file1;\r\n");
      out.write("\tfunction handleImgFileSelect1(e) {\r\n");
      out.write("\t\t  var files = e.target.files;\r\n");
      out.write("\t\t  var fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("\t\t  //이 코드가 존재하는 함수의 매개변수로 넘어온 값들을 array로 변환하겠다는 것\r\n");
      out.write("\t\t  //  https://tbang.tistory.com/132\r\n");
      out.write("\t\t  //console.log(fileArr);\r\n");
      out.write("\t\t  fileArr.forEach(function(f){\r\n");
      out.write("\t\t    \tif(!f.type.match(\"image.*\")){\r\n");
      out.write("\t\t        \talert(\"이미지 확장자만 업로드 가능합니다.\");\r\n");
      out.write("\t\t            return;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \tsel_file1=f;\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t var reader = new FileReader();\r\n");
      out.write("\t\t         reader.onload = function(e){\r\n");
      out.write("\t\t        \t //파일을 읽기에 성공하면 e 변수로 접근\r\n");
      out.write("\t\t\t         //이미지 Tag의 SRC속성에 읽어들인 File내용을 지정\r\n");
      out.write("\t\t\t         //alert(e.target.result);\r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t        \t $(\"#f_rcp_ord_img\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t        \t //src에 e.target.result\r\n");
      out.write("\t\t        \t// html태그 중 id 가 empImg 인 태그에 src 속성 값을 읽은 파일로 변경 ( src = \"파일에서 읽은 값 즉 파일\")\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t            reader.readAsDataURL(f);\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t}    \r\n");
      out.write("\t/* 요리 이미지 생성 */\r\n");
      out.write("\t\r\n");
      out.write("\t/* 유효성 체크 */\r\n");
      out.write("\t\r\n");
      out.write("\tfunction checkForm() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.RecipeForm.f_rcp_title.value==\"\"){\r\n");
      out.write("\t\t\talert(\" 제목을 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.RecipeForm.f_rcp_title.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 유효성 체크 */\r\n");
      out.write("\r\n");
      out.write("\t\t         \r\n");
      out.write("</script>\r\n");
      out.write("<!-- header -->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"skipnavi\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#container_title\">본문바로가기</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t<div class=\"preloader\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<div class=\"loader\">\r\n");
      out.write("\t\t\t\t<span class=\"loading\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"./RecipeWriteAction.re\" method=\"post\" enctype=\"multipart/form-data\" name=\"RecipeForm\" onsubmit=\"return checkForm();\">\r\n");
      out.write("\t<!-- ------------------본문시작 ------------------------ -->\r\n");
      out.write(" \t<div class=\"container\"> \r\n");
      out.write("\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<h1>레시피 등록</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-sm-12 \">\r\n");
      out.write("\t\t\t<div class=\"form-group title01\">\r\n");
      out.write("\t\t\t\t<!-- 레시피 썸네일 -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group t_img\" >\r\n");
      out.write("\t\t\t\t<img id=\"thumb_img\" name=\"f_rcp_th_img\"><br>\r\n");
      out.write("\t\t\t\t<input type=\"file\" id=\"input_thum_img\" name=\"input_thum_img\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 레시피 제목 -->\r\n");
      out.write("\t\t\t\t<div class=\"a01\">\r\n");
      out.write("\t\t\t\t<label for=\"r_1\"><h2>레시피 제목</h2></label><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"f_rcp_title\" placeholder=\"예)소고기 미역국 끓이기\"\r\n");
      out.write("\t\t\t\tstyle=\"width:400px;\"><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 요리 소개 -->\r\n");
      out.write("\t\t\t\t<div class=\"a02\">\r\n");
      out.write("\t\t\t\t<label for=\"r_2\"><h2>요리 소개</h2></label><br>\r\n");
      out.write("\t\t\t\t<textarea name=\"f_rcp_content\" placeholder=\"예) 이 레시피의 탄생 배경을 적어주세요\" \r\n");
      out.write("\t\t\t\tstyle=\"width:400px; height: 180px\"></textarea><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 카테고리 -->\r\n");
      out.write("\t\t\t\t<div class=\"a03\">\r\n");
      out.write("\t\t\t\t<label for=\"r_3\"><h2>카테고리</h2></label><br>\r\n");
      out.write("\t\t\t\t<select name=\"category\" id=\"category\">\r\n");
      out.write("\t\t\t\t<option value=\"1\">국/탕</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">볶음/반찬</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">분식</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">간식/디저트</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">술이한잔</option>\r\n");
      out.write("\t\t\t\t<option value=\"6\">캠핑/여행</option>\r\n");
      out.write("\t\t\t\t<option value=\"7\">고기류</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">해물류</option>\r\n");
      out.write("\t\t\t\t<option value=\"9\">헬씨/다이어트</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"col-sm-12 size\">\r\n");
      out.write("\t\t\t<div class=\"form-group ingredi\">\r\n");
      out.write("\t\t\t\t<!-- 재료 -->\r\n");
      out.write("\t\t\t\t<label for=\"r_4\"><h2>재료</h2></label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span class=\"warning\"> 3개까지만 추가 가능합니다. </span><br>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t \t<input type=\"text\" name=\"f_rcp_ingre0\"  placeholder=\"돼지고기\" id=\"R_ingre\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"f_rcp_ingre0\"  placeholder=\"300g\" id=\"R_ingre\"> \r\n");
      out.write("\t\t\t\t\t<div id=\"addedIngre\"></div><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"button-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"addIngre()\" value=\"추가\" class=\"btn-primary\"> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"delIngre()\" value=\"삭제\" class=\"btn-primary\"> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group01 order\">\r\n");
      out.write("\t\t\t\t<!-- 요리순서 -->\r\n");
      out.write("\t\t\t\t<label for=\"\" id=\"\"><h2>요리순서</h2></label>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<span class=\"warning\"> 3개까지만 추가 가능합니다. </span><br>\r\n");
      out.write("\t\t\t\t\t<textarea name=\"f_rcp_ord_text\" style=\"height: 150px; width: 300px;\"\r\n");
      out.write("\t\t\t \t\tplaceholder=\"예)소고기는 기름기를 떼어내고 적당한 크기로 썰어주세요\"></textarea>\r\n");
      out.write("\t\t\t\t\t<img id=\"f_rcp_ord_img\" class=\"f_rcp_ord_img\"><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" id=\"ord_img_upload\" name=\"ord_img_upload\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t \t\t<input type=\"button\" class=\"AddCuisine btn-primary\" value=\"추가\" >\r\n");
      out.write("\t\t\t \t\t<div id=\"addedCuisine\"></div>\r\n");
      out.write("\t\t\t \t\t\r\n");
      out.write("\t\t\t \t\t<!-- 해시태그 -->\r\n");
      out.write("\t\t\t \t\t<div class=\"tag\">\r\n");
      out.write("\t\t\t\t\t\t<p id=\"hashtag\"><h2>해시태그</h2></p><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"f_rcp_hashtag\" id=\"hashtag\"><br>\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 요리등록 & 삭제 -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"요리등록\" class=\"btn-primary regi\" >\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"모두삭제\" class=\"btn-primary regi\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 요리완성사진 -->\r\n");
      out.write("\t\t\t<!-- <div id=\"\" class=\"form-group\" >\r\n");
      out.write("\t\t\t<label for=\"\" id=\"\"><h2>요리 완성사진</h2></label><br>\r\n");
      out.write("\t\t\t\t<input type=\"file\" name=\"f_rcp_ord_img0\" id=\"f_rcp_imgs_upload\" multiple=\"multiple\"> <br>\r\n");
      out.write("\t\t\t\t\t<div id=\"imagePreview\">\r\n");
      out.write("\t\t\t\t\t<div class=\"f_rcp_imgs\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" >\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write(" </div> \r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/footer.jsp", out, false);
      out.write("    \r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-3.5.1.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t/* 대표 이미지 생성 */\r\n");
      out.write("\t\tvar sel_file;\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t//대표 이미지 \r\n");
      out.write("\t\t$(\"#input_thum_img\").on(\"change\", handleImgFileSelect);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction handleImgFileSelect(e) {\r\n");
      out.write("\t\t  var files = e.target.files;\r\n");
      out.write("\t\t  var fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  fileArr.forEach(function(f){\r\n");
      out.write("\t\t    \tif(!f.type.match(\"image.*\")){\r\n");
      out.write("\t\t        \talert(\"이미지 확장자만 업로드 가능합니다.\");\r\n");
      out.write("\t\t            return;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \tsel_file=f;\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t var reader = new FileReader();\r\n");
      out.write("\t\t    \t \r\n");
      out.write("\t\t    \t //alert(sel_file);\r\n");
      out.write("\t\t         reader.onload = function(e){\r\n");
      out.write("\t\t        \t $(\"#thumb_img\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t            reader.readAsDataURL(f);\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t} \r\n");
      out.write("\t/* 대표 이미지 생성 */\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t/* 재료 추가  */\r\n");
      out.write("\t\r\n");
      out.write("  var count = 1;\r\n");
      out.write(" \r\n");
      out.write("  function addIngre(){\r\n");
      out.write("  var addedIngre = document.getElementById(\"addedIngre\");\r\n");
      out.write(" \r\n");
      out.write("  var str = \"\";\r\n");
      out.write(" \r\n");
      out.write("  str+=\"<br><input type='text' name='f_rcp_ingre\"+count+\"' class='form-control form-control-sm' id='R_ingre'>\";\r\n");
      out.write("  str+=\"<input type='text' name='f_rcp_ingre\"+count+\"' class='form-control form-control-sm' id='R_ingre'>\";\r\n");
      out.write(" \r\n");
      out.write("  // 추가할 폼(에 들어갈 HTML)\r\n");
      out.write(" \r\n");
      out.write(" if(count<=3){\r\n");
      out.write("\t  var addedDiv = document.createElement(\"div\"); // 폼 생성\r\n");
      out.write("\t  addedDiv.id = \"added_\"+count; // 폼 Div에 ID 부여 (삭제를 위해)\r\n");
      out.write("\t  addedDiv.innerHTML = str; // 폼 Div안에 HTML삽입\r\n");
      out.write("\t  addedIngre.appendChild(addedDiv); // 삽입할 DIV에 생성한 폼 삽입\r\n");
      out.write("\t \r\n");
      out.write("\t  count++;\r\n");
      out.write("\t console.log(\"count:\"+count);\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t alert(\"3개까지 추가 가능합니다\");\r\n");
      out.write("\t }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  function delIngre(){\r\n");
      out.write("\t \r\n");
      out.write("\t  var addedIngre = document.getElementById(\"addedIngre\");\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t  if(count >=1){ // 현재 생성된 폼이 하나 이상이면\r\n");
      out.write("\t \r\n");
      out.write("\t  var addedDiv = document.getElementById(\"added_\"+(--count));\r\n");
      out.write("\t  // 마지막으로 생성된 폼의 ID를 통해 Div객체를 가져옴\r\n");
      out.write("\t  console.log(\"count :\"+count)\r\n");
      out.write("\t  \r\n");
      out.write("\t  addedIngre.removeChild(addedDiv); // 폼 삭제\r\n");
      out.write("\t \r\n");
      out.write("\t  }else{ // 마지막 폼만 남아있다면\r\n");
      out.write("\t \r\n");
      out.write("\t  document.addedIngre.reset(); // 폼 내용 삭제\r\n");
      out.write("\t \r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write(" \r\n");
      out.write("  } \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t/* 재료 추가 끝 */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t// 이미지 순서(0) 들어가는 코드\r\n");
      out.write("\t$(\"#ord_img_upload\").on(\"change\", handleImgFileSelect1);\r\n");
      out.write("\t\r\n");
      out.write("\t/* 요리 순서 이미지(0) 생성 */\r\n");
      out.write("\t var sel_file1;\r\n");
      out.write("\tfunction handleImgFileSelect1(e) {\r\n");
      out.write("\t\t  var files = e.target.files;\r\n");
      out.write("\t\t  var fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("\t\t  //이 코드가 존재하는 함수의 매개변수로 넘어온 값들을 array로 변환하겠다는 것\r\n");
      out.write("\t\t  //  https://tbang.tistory.com/132\r\n");
      out.write("\t\t  //console.log(fileArr);\r\n");
      out.write("\t\t  fileArr.forEach(function(f){\r\n");
      out.write("\t\t    \tif(!f.type.match(\"image.*\")){\r\n");
      out.write("\t\t        \talert(\"이미지 확장자만 업로드 가능합니다.\");\r\n");
      out.write("\t\t            return;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \tsel_file1=f;\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t var reader = new FileReader();\r\n");
      out.write("\t\t         reader.onload = function(e){\r\n");
      out.write("\t\t        \t //파일을 읽기에 성공하면 e 변수로 접근\r\n");
      out.write("\t\t\t         //이미지 Tag의 SRC속성에 읽어들인 File내용을 지정\r\n");
      out.write("\t\t\t         //alert(e.target.result);\r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t        \t $(\"#f_rcp_ord_img\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t        \t //src에 e.target.result\r\n");
      out.write("\t\t        \t// html태그 중 id 가 empImg 인 태그에 src 속성 값을 읽은 파일로 변경 ( src = \"파일에서 읽은 값 즉 파일\")\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t            reader.readAsDataURL(f);\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* 요리 순서 추가 생성 */\r\n");
      out.write("\t\r\n");
      out.write("\tvar CuiNum=1;\r\n");
      out.write("\t$('.AddCuisine').on(\"click\",function(){\r\n");
      out.write("\t\tif($(\"textarea[name^='ord_text']\").length<=2){\r\n");
      out.write("\t\t\t $('#addedCuisine').append(\r\n");
      out.write("\t\t\t\t\t '<div id=\"ac'+CuiNum+'\">'\r\n");
      out.write("\t\t\t\t\t +'<textarea name=\"ord_text'+CuiNum+'\" style=\"height: 150px; width: 300px;\"></textarea>'\r\n");
      out.write("\t\t\t\t\t +'<img src=\"\" id=\"f_rcp_ord_imgfile'+CuiNum+'\" name=\"f_rcp_ord_imgfile'+CuiNum+'\" class=\"f_rcp_ord_imgfile'+CuiNum+'\">'\r\n");
      out.write("\t\t\t\t\t +'<input type=\"button\" class=\"OrdRemove'+CuiNum+' btn-primary\" value=\"삭제\"></button>'\r\n");
      out.write("\t\t\t\t \t +'<input type=\"file\" id=\"ord_img_upload'+CuiNum+'\" name=\"ord_img_upload'+CuiNum+'\" class=\"ord_img_upload'+CuiNum+'\">'\r\n");
      out.write("\t\t\t\t\t +'</div>'\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t ); //input 추가\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\t alert(\"3개까지만 추가 가능합니다.\")\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tvar OrdRemove=\".OrdRemove\"+CuiNum;\r\n");
      out.write("\t\tvar ac=\"#ac\"+CuiNum;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t $(OrdRemove).on('click',function(){\r\n");
      out.write("\t\t console.log(\"ac:\"+ac)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t $(ac).remove(); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tCuiNum++;\r\n");
      out.write("\t\tconsole.log(\"CuiNum:\"+CuiNum); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t//이미지 순서(1~3) 들어가는 코드\r\n");
      out.write("\t\t\tvar ImgStep=CuiNum-1;\r\n");
      out.write("\t\t\tconsole.log(\"ImgStep :\"+ImgStep)\r\n");
      out.write("\t\t\tvar AddOrdUpload=\"#ord_img_upload\"+(ImgStep);\r\n");
      out.write("\t\t\tvar AddOrdImg=\"#f_rcp_ord_imgfile\"+(ImgStep);\r\n");
      out.write("\t\t\tconsole.log(\"AddOrdUpload :\"+AddOrdUpload)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$(AddOrdUpload).on(\"change\", handleImgFileSelect3);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/* 요리 순서 이미지(1~3) 생성 */\r\n");
      out.write("\tvar sel_file2;\r\n");
      out.write("\tfunction handleImgFileSelect3(e) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  var files = e.target.files;\r\n");
      out.write("\t\t  var fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("\r\n");
      out.write("\t\t  fileArr.forEach(function(f){\r\n");
      out.write("\t\t    \tif(!f.type.match(\"image.*\")){\r\n");
      out.write("\t\t        \talert(\"이미지 확장자만 업로드 가능합니다.\");\r\n");
      out.write("\t\t            return;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \tsel_file2=f;\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t var reader = new FileReader();\r\n");
      out.write("\t\t         reader.onload = function(e){\r\n");
      out.write("\r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t        \t $(AddOrdImg).attr(\"src\",e.target.result);\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t            reader.readAsDataURL(f);\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t/* 요리 순서 이미지(1~3) 미리보기 생성 끝 */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
