/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-05-30 06:24:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.goodRes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;
import java.util.HashMap;
import com.goodres.db.GoodResDAO;
import java.util.List;
import com.goodres.db.GoodResBoardBean;

public final class goodres_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.goodres.db.GoodResDAO");
    _jspx_imports_classes.add("com.goodres.db.GoodResBoardBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>라따뚜이</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/common.css?20200924090025\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.cjcookit.com/cjkit/web/css/main.css?20200924090025\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./cjkit/web/css/goodResCSS/goodress_main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");

		
		GoodResBoardBean grbb = new GoodResBoardBean();
		
		List<GoodResBoardBean> goodResList = new ArrayList<GoodResBoardBean>();
		List<GoodResBoardBean> goodResTypeList = new ArrayList<GoodResBoardBean>();
		List<GoodResBoardBean> starAvgList = new ArrayList<GoodResBoardBean>();
		List<GoodResBoardBean> foodTypeList = new ArrayList<GoodResBoardBean>();
	
		String[] gu1 = {"강서구","금정구","기장군","남구","동구","동래구",
						"부산진구","북구","사상구","사하구","서구","수영구",
						"연제구","영도구","중구","해운대구"};
		
		HashMap<String, List<GoodResBoardBean>> totalList = new HashMap<>();
		HashMap<String, List<GoodResBoardBean>> totalTypeList = new HashMap<>();
		HashMap<String, List<GoodResBoardBean>> foodTypeMap = new HashMap<>();
		
		totalList = (HashMap) request.getAttribute("totalList");
		totalTypeList = (HashMap) request.getAttribute("totalTypeList");
		foodTypeMap = (HashMap) request.getAttribute("foodTypeMap");
		
		//System.out.println(foodTypeMap);
		
		starAvgList = (List) request.getAttribute("starAvgList");
		
		String[] foodTypeKeys = foodTypeMap.keySet().toArray(new String[foodTypeMap.size()]);
		
		//System.out.println("foodTypeKeys>>>>> " + foodTypeKeys.length);
		
		/* 
        for (String key : foodTypeKeys) {
            System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" + key);
        }
         */
		int idx = 0;
		String b = "";
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" \t<div class=\"div_gr_main\">\r\n");
      out.write("\t\t<div class=\"div_search\">\r\n");
      out.write("\t\t\t<form action=\"./GoodResSearchAction.gr\" method=\"post\">\t\t\t\r\n");
      out.write("\t\t\t\t<table class=\"div_search_table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"div_search_input01\" type=\"text\" name=\"gr_input_keyword_search\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"div_search_input02\" type=\"submit\" name=\"gr_btn_search\" value=\"검색\"></td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 지역별======================================================================= -->\r\n");
      out.write("\t\t<div class=\"div_gr_total_list\">\r\n");
      out.write("\t\t\t<div class=\"div_gr_list\">\r\n");
      out.write("\t\t\t\t<div class=\"div_gr_list_span\">부산 지역(구) 맛집 리스트</div>\r\n");
      out.write("\t\t\t\t<table class=\"div_gr_list_table\">\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
					
							int[] save = new int[3];		
							
							for(int i=0; i<save.length; i++) {						
								save[i] = (int)(Math.random()*gu1.length); // gu1.length == 16
								
								for(int j=0; j<i; j++) {
									if(save[i] == save[j]) {
										i--;
										break;
									}
								}						
							}
							
							for(int i=0;i<3;i++) {
								goodResList = totalList.get(gu1[save[i]]);
								grbb = goodResList.get(0);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<!-- 이미지 출력 -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./GoodResList.gr?gu=");
      out.print(grbb.getF_gr_gu() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(grbb.getF_gr_img() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t \t\t\t\t\t");

	 						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");

							for(int i=0; i<3; i++) {
								goodResList = totalList.get(gu1[save[i]]);
								grbb = goodResList.get(0);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"gr_gu_name\">");
      out.print(grbb.getF_gr_gu() );
      out.write(" 맛집</td>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\t\t\t\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 평점별======================================================================= -->\r\n");
      out.write("\t\t\t<div class=\"div_gr_list2\">\r\n");
      out.write("\t\t\t\t<span class=\"div_gr_list_span2\">평점이 높은 인기 식당</span>\r\n");
      out.write("\t\t\t\t<table class=\"div_gr_list_table2\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");

	 					for(int i=0;i<3;i++) {
								grbb = starAvgList.get(i);						
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<!-- 이미지 출력 -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./GoodResContentAction.gr?num=");
      out.print(grbb.getF_gr_num() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(grbb.getF_gr_img() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t \t\t\t\t");

	 					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");

						for(int i=0; i<3; i++) {
							grbb = starAvgList.get(i);
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"gr_gu_name\">");
      out.print(grbb.getF_gr_name() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 메뉴별======================================================================= -->\r\n");
      out.write("\t\t\t<div class=\"div_gr_list3\">\r\n");
      out.write("\t\t\t\t<span class=\"div_gr_list_span3\">메뉴별 인기 맛집</span>\r\n");
      out.write("\t\t\t\t<table class=\"div_gr_list_table3\">\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
					
							int[] save2 = new int[3];		
							
							for(int i=0; i<save2.length; i++) {						
								save2[i] = (int)(Math.random()*foodTypeKeys.length); // foodTypeKeys.length == 17
								
								for(int j=0; j<i; j++) {
									if(save2[i] == save2[j]) {
										i--;
										break;
									}
								}						
							}
							
							for(int i=0;i<3;i++) {
								foodTypeList = foodTypeMap.get(foodTypeKeys[save2[i]]);								
								grbb = foodTypeList.get(0);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<!-- 이미지 출력 -->\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./GoodResList.gr?foodtype=");
      out.print(grbb.getF_gr_foodtype() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(grbb.getF_gr_img() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t \t\t\t\t\t");

	 						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t");

							for(int i=0; i<3; i++) {
								foodTypeList = foodTypeMap.get(foodTypeKeys[save2[i]]);
								grbb = foodTypeList.get(0);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td class=\"gr_gu_name\">");
      out.print(grbb.getF_gr_foodtype() );
      out.write(" 맛집</td>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
